/* ============================================================
   WeX EDUCATION — DATA.JS
   Toàn bộ dữ liệu: HSA MegaEdu + SGK + Thầy Chí + Cô Sen
   ============================================================ */

const MEGA_SUBJECTS = [
  {id:'toan_co_ban',name:'TOÁN CƠ BẢN',desc:'Toán · HSA · Chuyên đề 12',icon:'fa-calculator',color:'green',group:'hsa',lessons:[
    {name:'Khoảng cách từ điểm đến mp-Góc trong KG',date:'10/04',link:'https://www.youtube.com/watch?v=jEJu4H_cUSs',type:'video'},
    {name:'Khoảng cách từ điểm đến MP ( tiếp)',date:'17/04',link:'https://www.youtube.com/watch?v=t3Vw_yxlgHI',type:'video'},
    {name:'Khoảng cách giữa 2 ĐT chéo nhau',date:'24/04',link:'https://www.youtube.com/watch?v=LQQrSZvD5Os',type:'video'},
    {name:'Công thức DKH tính KC giữa 2 ĐT',date:'05/05',link:'https://www.youtube.com/watch?v=tgPdx8EEfsk',type:'video'},
    {name:'Công thức DKH tính KC giữa 2 ĐT-TIẾP',date:'08/05',link:'https://www.youtube.com/watch?v=FZ1xjaVf38s',type:'video'},
    {name:'Thể tích',date:'12/05',link:'https://www.youtube.com/watch?v=c9cIE6m6r3c',type:'video'},
    {name:'Tính đơn điệu của hàm số',date:'15/05',link:'https://www.youtube.com/watch?v=kagwiaGQ00I',type:'video'},
    {name:'Cực trị của hàm số',date:'19/05',link:'https://www.youtube.com/watch?v=Hv38t3-E6ME',type:'video'},
    {name:'GTLN-GTNN của hàm số',date:'22/05',link:'https://www.youtube.com/watch?v=hsAErSmUpUc',type:'video'},
    {name:'Đường tiệm cận của Đồ thị hàm số',date:'26/05',link:'https://www.youtube.com/watch?v=SZPl80hyXCo',type:'video'},
    {name:'Khảo sát sự Biến thiên và vẽ ĐTHS',date:'29/05',link:'https://www.youtube.com/watch?v=8a9rXTS750M',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ T5 - ĐỊNH LƯỢNG',date:'01/06',link:'https://www.youtube.com/watch?v=zL5faREUzLQ',type:'video'},
    {name:'Khảo sát hàm phân thức',date:'03/06',link:'https://www.youtube.com/watch?v=WrugSPSW6t4',type:'video'},
    {name:'Khảo sát hàm phân thức-Tiếp',date:'06/06',link:'https://www.youtube.com/watch?v=nk7Gse2CK40',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://www.youtube.com/watch?v=rhlaiNxmki0',type:'video'},
    {name:'Cực trị của Hàm hợp',date:'12/06',link:'https://www.youtube.com/watch?v=mYKfj3T6tm0',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp-Tiếp',date:'16/06',link:'https://www.youtube.com/watch?v=yaRCocsWjXw',type:'video'},
    {name:'GTLN-GTNN của Hàm hợp',date:'19/06',link:'https://www.youtube.com/watch?v=OAgwmfNl6mI',type:'video'},
    {name:'Tương giao của Đồ thị HS',date:'23/06',link:'https://www.youtube.com/watch?v=XiXOX9xnWzE',type:'video'},
    {name:'Tương giao của Đồ thị HS - Tiếp',date:'27/06',link:'https://www.youtube.com/watch?v=9xQu8B1bAJA',type:'video'},
    {name:'(Có tham số) Tính đơn điệu của Hàm số',date:'30/06',link:'https://www.youtube.com/watch?v=9JJQGipRT54',type:'video'},
    {name:'(Có tham số) Tính đơn điệu của Hàm số - Tiếp',date:'03/07',link:'https://www.youtube.com/watch?v=pYglUBnSSJU',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P1)',date:'07/07',link:'https://www.youtube.com/watch?v=qcfXhfvBTyU',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P1) - Tiếp',date:'10/07',link:'https://www.youtube.com/watch?v=3GW8z4P6wvQ',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P2)',date:'14/07',link:'https://www.youtube.com/watch?v=R4BmwVUUiZg',type:'video'},
    {name:'Biện luận số nghiệm của PT',date:'17/07',link:'https://www.youtube.com/watch?v=tglFDtvHiG0',type:'video'},
    {name:'Biện luận số nghiệm của PT - Tiếp',date:'21/07',link:'https://www.youtube.com/watch?v=JW0GrPcDrGE',type:'video'},
    {name:'Đường tiệm cận chứa tham số m',date:'24/07',link:'https://www.youtube.com/watch?v=Fk_4Kk-39bA',type:'video'},
    {name:'Vectơ và các phép toán vectơ trong không gian',date:'28/07',link:'https://www.youtube.com/watch?v=y3MqAmS6icI',type:'video'},
    {name:'Vectơ và các phép toán vectơ trong không gian - Tiếp',date:'31/07',link:'https://www.youtube.com/watch?v=J1igzZW_i_s',type:'video'},
    {name:'Hệ trục toạ độ trong không gian',date:'04/08',link:'https://www.youtube.com/watch?v=gHYXMiebGY8',type:'video'},
    {name:'Hệ trục toạ độ trong không gian - Tiếp',date:'06/08',link:'https://www.youtube.com/watch?v=cMJ77JGb44Y',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ THÁNG 7',date:'10/08',link:'https://www.youtube.com/watch?v=ZzIjOyG8Dv8',type:'video'},
    {name:'Biểu thức toạ độ của các phép toán vectơ',date:'11/08',link:'https://www.youtube.com/watch?v=i1s2L1v9MUw',type:'video'},
    {name:'Biểu thức toạ độ của các phép toán vectơ - Tiếp',date:'14/08',link:'https://www.youtube.com/watch?v=hHdeZUGo5hc',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://www.youtube.com/watch?v=WuQVuuUC-Mc',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng - Tiếp',date:'21/08',link:'https://www.youtube.com/watch?v=PJokQjhQlpM',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng - Tiếp',date:'25/08',link:'https://www.youtube.com/watch?v=m5A9BMaSni4',type:'video'},
    {name:'B19. Mẫu số liệu (P1) + Phương sai và độ lệch chuẩn (P2)',date:'28/08',link:'https://www.youtube.com/watch?v=-umtsPNjfos',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ ĐỊNH LƯỢNG THÁNG',date:'04/09',link:'https://www.youtube.com/watch?v=n9pc8PtU7SU',type:'video'},
    {name:'B20. Nguyên hàm và tính chất của nguyên hàm',date:'08/09',link:'https://www.youtube.com/watch?v=oIKRJeF95KQ',type:'video'},
    {name:'B20. Nguyên hàm và tính chất của nguyên hàm - Tiếp',date:'11/09',link:'https://www.youtube.com/watch?v=zpvTcO6idms',type:'video'},
    {name:'TL: Khoảng cách từ điểm đến mp-Góc trong KG',date:'10/04',link:'https://drive.google.com/uc?export=download&id=1EnwCYK-TqJRkaQIsvye5pBHS-IPw8lzs',type:'tailieu'},
    {name:'TL: Khoảng cách giữa 2 ĐT chéo nhau',date:'24/04',link:'https://drive.google.com/uc?export=download&id=1MtQfAsKQUn0mmNvoata1vMqzj4rGZrK6',type:'tailieu'},
    {name:'TL: Công thức DKH tính KC giữa 2 ĐT',date:'05/05',link:'https://drive.google.com/uc?export=download&id=1UQnyq-T08COsQ_lnRsLr2OBLFd3wxW-d',type:'tailieu'},
    {name:'TL: Thể tích',date:'12/05',link:'https://drive.google.com/uc?export=download&id=1XnC0qR5qStNQZi0oToLEzrhEeuHSSaEC',type:'tailieu'},
    {name:'TL: Tính đơn điệu của hàm số',date:'15/05',link:'https://drive.google.com/uc?export=download&id=1MUqJmD_jQ1xborohVlnYt-bkoRnAyX1l',type:'tailieu'},
    {name:'TL: Cực trị của hàm số',date:'19/05',link:'https://drive.google.com/uc?export=download&id=1lCQDr4ObqjT_pc9Uqndv7TtN-MAo_1qW',type:'tailieu'},
    {name:'TL: GTLN-GTNN của hàm số',date:'22/05',link:'https://drive.google.com/uc?export=download&id=1bd_SpGrNtqbBabHdrsZMKJIFaecxjdOF',type:'tailieu'},
    {name:'TL: Đường tiệm cận của Đồ thị hàm số',date:'26/05',link:'https://drive.google.com/uc?export=download&id=1FVcsvnu8TcPjAqYGXmXohkocaqMGtpsa',type:'tailieu'},
    {name:'TL: Khảo sát sự Biến thiên và vẽ ĐTHS',date:'29/05',link:'https://drive.google.com/uc?export=download&id=1p9oeVj1_0WKnFe7BYuWDgcPHJ-C9tgwN',type:'tailieu'},
    {name:'TL: CHỮA ĐỀ THI THỬ T5 - ĐỊNH LƯỢNG',date:'01/06',link:'https://drive.google.com/uc?export=download&id=1uOwdW7NsAHpqbPmK-Pf93z8ddJVIUkGm',type:'tailieu'},
    {name:'TL: Khảo sát hàm phân thức',date:'03/06',link:'https://drive.google.com/uc?export=download&id=1ln43kZyckL_msziP9Wgf-t8BzxCV2mKX',type:'tailieu'},
    {name:'TL: Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://drive.google.com/uc?export=download&id=1y9LN43DOa6ZG7KYjDg0o2wegFM53bOmC',type:'tailieu'},
    {name:'TL: Cực trị của Hàm hợp',date:'12/06',link:'https://drive.google.com/uc?export=download&id=1qSyfGWfBuN0hJjgaPiXqSPAwjXomoTA7',type:'tailieu'},
    {name:'TL: GTLN-GTNN của Hàm hợp',date:'19/06',link:'https://drive.google.com/uc?export=download&id=1QWJc8BVh4O2zpsJgIQyjgmIfX-q1Qo33',type:'tailieu'},
    {name:'TL: Tương giao của Đồ thị HS',date:'23/06',link:'https://drive.google.com/uc?export=download&id=1v3_C7_gbjYptAVzo9v3TYptSlks3KT3y',type:'tailieu'},
    {name:'TL: (Có tham số) Tính đơn điệu của Hàm số',date:'30/06',link:'https://drive.google.com/uc?export=download&id=1COrcjYnn-eA1jRoq2Kjgb52GB-c3fICL',type:'tailieu'},
    {name:'TL: (Có tham số) Cực trị của Hàm số (P1)',date:'07/07',link:'https://drive.google.com/uc?export=download&id=1TgtcJVwR7fOyzJEEK3s2jjIU3UZLkHM8',type:'tailieu'},
    {name:'TL: (Có tham số) Cực trị của Hàm số (P2)',date:'14/07',link:'https://drive.google.com/uc?export=download&id=1kuVTvXxzIGCXDdxFWf9BmcdYANSKnsJ5',type:'tailieu'},
    {name:'TL: Biện luận số nghiệm của PT',date:'17/07',link:'https://drive.google.com/uc?export=download&id=1aRymNExby_zqZu9NzQ1HhtW3S3ykPijH',type:'tailieu'},
    {name:'TL: Đường tiệm cận chứa tham số m',date:'24/07',link:'https://drive.google.com/uc?export=download&id=1E50-hJDJ-i4EKnVvLxmZh7iX-aLvYmjl',type:'tailieu'},
    {name:'TL: Vectơ và các phép toán vectơ trong không gian',date:'28/07',link:'https://drive.google.com/uc?export=download&id=1mMGL83Q-VSPqm6W7I-hsnzPAZ9jsQNVG',type:'tailieu'},
    {name:'TL: Hệ trục toạ độ trong không gian',date:'04/08',link:'https://drive.google.com/uc?export=download&id=1Dx1U8XUBOx6GAEruY6dONEoNN10BO1LW',type:'tailieu'},
    {name:'TL: Biểu thức toạ độ của các phép toán vectơ',date:'11/08',link:'https://drive.google.com/uc?export=download&id=1uFltDt1Iom2HmJ8RtrNxFdUZAVX6Q5al',type:'tailieu'},
    {name:'TL: B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://drive.google.com/uc?export=download&id=1lqj0SQ5TGsdhYxX-SdE0TViI2g4Wg3uj',type:'tailieu'},
    {name:'TL: B19. Mẫu số liệu + Phương sai',date:'28/08',link:'https://drive.google.com/uc?export=download&id=1a1nG_N4OyCEsMGg84Bq-tWlb0EVfDO7a',type:'tailieu'},
    {name:'TL: B20. Nguyên hàm và tính chất',date:'08/09',link:'https://drive.google.com/uc?export=download&id=1Q3UnmahuvEt-XsOiT2RWra-tHxSSJvme',type:'tailieu'},
    {name:'BTVN: Khoảng cách từ điểm đến mp',date:'10/04',link:'https://drive.google.com/drive/folders/1GtjZE100qb87gZvYuOc4s-GGj6dD6YES',type:'btvn'},
    {name:'Chữa BTVN: Tính đơn điệu',date:'19/05',link:'https://drive.google.com/file/d/1HAOxa3KSPE5C9RiUD7Pkk5m1bcirFgg-/view',type:'btvn'},
    {name:'BTVN + Chữa: Nguyên hàm',date:'08/09',link:'https://drive.google.com/drive/folders/1GQNP0JxTphcJs-qBNyQ4BkLygwOuMZBC',type:'btvn'}
  ]},
  {id:'toan_nang_cao',name:'TOÁN NÂNG CAO',desc:'Toán · HSA · Chuyên đề nâng cao',icon:'fa-chart-line',color:'violet',group:'hsa',lessons:[
    {name:'Khoảng cách giữa 2 ĐT chéo nhau',date:'14/04',link:'https://www.youtube.com/watch?v=lkIdIf1aKSP4',type:'video'},
    {name:'Công thức DKH tính khoảng cách giữa 2 ĐT',date:'21/04',link:'https://www.youtube.com/watch?v=jBNvSSnaDSg',type:'video'},
    {name:'Thể tích',date:'28/04',link:'https://www.youtube.com/watch?v=q5YufpNSBSw',type:'video'},
    {name:'Thể tích (tiếp)',date:'05/05',link:'https://www.youtube.com/watch?v=GGbSRbenKQE',type:'video'},
    {name:'Bài toán nước dâng',date:'07/05',link:'https://www.youtube.com/watch?v=s26weHYHNPA',type:'video'},
    {name:'Tính đơn điệu của hàm số',date:'12/05',link:'https://www.youtube.com/watch?v=5hRO3HyzU5A',type:'video'},
    {name:'Cực trị của hàm số',date:'14/05',link:'https://www.youtube.com/watch?v=99z_rvIgmko',type:'video'},
    {name:'Chữa BT tính đơn điệu của hàm số',date:'19/05',link:'https://www.youtube.com/watch?v=1ZqhGy_Zdh0',type:'video'},
    {name:'GTLN-GTNN của hàm số',date:'21/05',link:'https://www.youtube.com/watch?v=ExCVQXMNYGs',type:'video'},
    {name:'Đường tiệm cận của Đồ thị hàm số',date:'26/05',link:'https://www.youtube.com/watch?v=oo1PlNrIork',type:'video'},
    {name:'Khảo sát sự Biến thiên và vẽ ĐTHS',date:'28/05',link:'https://www.youtube.com/watch?v=ZjNS83DGemA',type:'video'},
    {name:'Khảo sát hàm phân thức',date:'03/06',link:'https://www.youtube.com/watch?v=18OR9kzkG8M',type:'video'},
    {name:'Khảo sát hàm phân thức-Tiếp',date:'08/06',link:'https://www.youtube.com/watch?v=csL7LaTT8yI',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://www.youtube.com/watch?v=QBXPNii6PrI',type:'video'},
    {name:'Cực trị của hàm hợp',date:'11/06',link:'https://www.youtube.com/watch?v=VCYj7u5d8PI',type:'video'},
    {name:'GTLN-GTNN của Hàm hợp',date:'16/06',link:'https://www.youtube.com/watch?v=qeOeqnfIVfA',type:'video'},
    {name:'Chữa BTVN phần Hàm hợp (Bài 6+7)',date:'18/06',link:'https://www.youtube.com/watch?v=rqK1ReAIcow',type:'video'},
    {name:'Tương giao của Đồ thị HS',date:'23/06',link:'https://www.youtube.com/watch?v=b9v0wjZU0h4',type:'video'},
    {name:'(Có tham số) Tính đơn điệu của Hàm số',date:'30/06',link:'https://www.youtube.com/watch?v=KfYkNet0dig',type:'video'},
    {name:'(Có tham số) Tính đơn điệu - Tiếp',date:'02/07',link:'https://www.youtube.com/watch?v=55mQrZerLrw',type:'video'},
    {name:'Hàm số có chứa dấu GTTĐ',date:'04/07',link:'https://www.youtube.com/watch?v=uOAE8uqt0u4',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P1)',date:'07/07',link:'https://www.youtube.com/watch?v=Uv3bHBj-lHw',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P1) - Tiếp',date:'09/07',link:'https://www.youtube.com/watch?v=V5uc8vZSDd0',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P2)',date:'14/07',link:'https://www.youtube.com/watch?v=FCQvHw4gHgM',type:'video'},
    {name:'Biện luận số nghiệm của PT',date:'16/07',link:'https://www.youtube.com/watch?v=48P04cgewAU',type:'video'},
    {name:'Biện luận số nghiệm của PT -Tiếp',date:'21/07',link:'https://www.youtube.com/watch?v=3yFYMdBoL1s',type:'video'},
    {name:'Đường tiệm cận chứa tham số m',date:'23/07',link:'https://www.youtube.com/watch?v=wzz2ZJ2Ulq0',type:'video'},
    {name:'Vectơ và các phép toán vectơ trong không gian',date:'28/07',link:'https://www.youtube.com/watch?v=b31ncDC1hwE',type:'video'},
    {name:'Vectơ và các phép toán vectơ trong không gian-Tiếp',date:'30/07',link:'https://www.youtube.com/watch?v=AloZncV_56s',type:'video'},
    {name:'Hệ trục toạ độ trong không gian',date:'04/08',link:'https://www.youtube.com/watch?v=dtHvaqyI_Ao',type:'video'},
    {name:'Hệ trục toạ độ trong không gian - Tiếp',date:'06/08',link:'https://www.youtube.com/watch?v=GQupOI0Bq0U',type:'video'},
    {name:'Hệ trục toạ độ trong không gian - Tiếp',date:'11/08',link:'https://www.youtube.com/watch?v=QKubS93wUDo',type:'video'},
    {name:'Biểu thức toạ độ của các phép toán vectơ',date:'13/08',link:'https://www.youtube.com/watch?v=7fGquJpArys',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://www.youtube.com/watch?v=pUuIB4lb-yw',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng (ƯD)',date:'20/08',link:'https://www.youtube.com/watch?v=mXQlgz2rZF0',type:'video'},
    {name:'B18. Phương pháp trải phẳng hình',date:'25/08',link:'https://www.youtube.com/watch?v=OZVNpQyS4EY',type:'video'},
    {name:'B19. Mẫu số liệu + Phương sai',date:'27/08',link:'https://www.youtube.com/watch?v=GdIDx11inD8',type:'video'},
    {name:'B20. Nguyên hàm và tính chất',date:'03/09',link:'https://www.youtube.com/watch?v=SwdIimp4kOE',type:'video'},
    {name:'B20. Nguyên hàm - Tiếp',date:'08/09',link:'https://www.youtube.com/watch?v=VuG18ukcWOs',type:'video'},
    {name:'B21. Tích phân và tính chất',date:'10/09',link:'https://www.youtube.com/watch?v=aQva_PEDX0A',type:'video'},
    {name:'TL: Khoảng cách giữa 2 ĐT chéo nhau',date:'14/04',link:'https://drive.google.com/uc?export=download&id=1hcOTO_pSuiBCXxKyeDUYGrAns_5Celxk',type:'tailieu'},
    {name:'TL: Công thức DKH tính khoảng cách 2 ĐT',date:'21/04',link:'https://drive.google.com/uc?export=download&id=14h7QhNYSei77zSNeZV9MtBJQ4x4At7kP',type:'tailieu'},
    {name:'TL: Thể tích',date:'28/04',link:'https://drive.google.com/uc?export=download&id=11BgX9bAKKnSx6wrSgqnXMzuZkBCWUTmY',type:'tailieu'},
    {name:'TL: Bài toán nước dâng',date:'07/05',link:'https://drive.google.com/uc?export=download&id=1x6UCTQSgl8UsQJDUHTZbUJA22Yheg7mt',type:'tailieu'},
    {name:'TL: Tính đơn điệu của hàm số',date:'12/05',link:'https://drive.google.com/uc?export=download&id=1ajJ47vBi4W7ot5WjjPIfCqBODxoI1vAH',type:'tailieu'},
    {name:'TL: Cực trị của hàm số',date:'14/05',link:'https://drive.google.com/uc?export=download&id=14yEQkPcBnRcHiaTp1uzjia-0m0RilHCw',type:'tailieu'},
    {name:'TL: GTLN-GTNN của hàm số',date:'21/05',link:'https://drive.google.com/uc?export=download&id=1bMy5qAjSpCeciGP21gVLapjlw1SynRFu',type:'tailieu'},
    {name:'TL: Đường tiệm cận của Đồ thị hàm số',date:'26/05',link:'https://drive.google.com/uc?export=download&id=1gG6yhZuVuAMSZr-V6nSGkk17hp0susGb',type:'tailieu'},
    {name:'TL: Khảo sát sự Biến thiên và vẽ ĐTHS',date:'28/05',link:'https://drive.google.com/uc?export=download&id=1fefpv64K3L5aurvBtvm6jcbLbEFSvvbj',type:'tailieu'},
    {name:'TL: Khảo sát hàm phân thức',date:'03/06',link:'https://drive.google.com/uc?export=download&id=1ln43kZyckL_msziP9Wgf-t8BzxCV2mKX',type:'tailieu'},
    {name:'TL: Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://drive.google.com/uc?export=download&id=1-AAbuGPxm2btqK-OEm0oSRVXcmETsAVg',type:'tailieu'},
    {name:'TL: Cực trị của hàm hợp',date:'11/06',link:'https://drive.google.com/uc?export=download&id=1qtLBR88PK6-eKKWtr1VYCJ8OFVGI9BiI',type:'tailieu'},
    {name:'TL: GTLN-GTNN của Hàm hợp',date:'16/06',link:'https://drive.google.com/uc?export=download&id=1U1QrCGRap8l4v1iLaVB004klCQkvKn0S',type:'tailieu'},
    {name:'TL: Tương giao của Đồ thị HS',date:'23/06',link:'https://drive.google.com/uc?export=download&id=1mocGoYAsKB8C9KLliDarjhJEPA9cklqm',type:'tailieu'},
    {name:'TL: (Có tham số) Tính đơn điệu của Hàm số',date:'30/06',link:'https://drive.google.com/uc?export=download&id=1COrcjYnn-eA1jRoq2Kjgb52GB-c3fICL',type:'tailieu'},
    {name:'TL: (Có tham số) Cực trị của Hàm số (P1)',date:'07/07',link:'https://drive.google.com/uc?export=download&id=1IwQmUELDc3cznxHvTLsgKkLvuTDlD1-1',type:'tailieu'},
    {name:'TL: (Có tham số) Cực trị của Hàm số (P2)',date:'14/07',link:'https://drive.google.com/uc?export=download&id=1Yieikxa89UjGFRPQada3yfyMZ66NrPWg',type:'tailieu'},
    {name:'TL: Biện luận số nghiệm của PT',date:'16/07',link:'https://drive.google.com/uc?export=download&id=15lzP873vVdqBWvRN4_vm6J9iPoJSQc5T',type:'tailieu'},
    {name:'TL: Đường tiệm cận chứa tham số m',date:'23/07',link:'https://drive.google.com/uc?export=download&id=1PJoyNYTGfRW7ynIDpjK50gmFcWggwd8-',type:'tailieu'},
    {name:'TL: Vectơ và các phép toán vectơ KG',date:'28/07',link:'https://drive.google.com/uc?export=download&id=1K_teZnO8lXEFJ4r3-nPXQlRYJhlk-B_G',type:'tailieu'},
    {name:'TL: Hệ trục toạ độ trong không gian',date:'04/08',link:'https://drive.google.com/uc?export=download&id=1twk0mknQGTqz-qT-0K8nyt2JJ10ne5n4',type:'tailieu'},
    {name:'TL: Biểu thức toạ độ các phép toán vectơ',date:'13/08',link:'https://drive.google.com/uc?export=download&id=1YhB1YKf5QZcGkM3WB8eerhufAkDp0mOo',type:'tailieu'},
    {name:'TL: B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://drive.google.com/uc?export=download&id=1w28yNmd58zdbKMyq6wHOow6dyuiiJ1fU',type:'tailieu'},
    {name:'TL: B18. Phương pháp trải phẳng hình',date:'25/08',link:'https://drive.google.com/uc?export=download&id=1q9K7ngJW_0kdvZEVOx2vc9CztmKlTpxe',type:'tailieu'},
    {name:'TL: B19. Mẫu số liệu + Phương sai',date:'27/08',link:'https://drive.google.com/uc?export=download&id=1UzBQL10CxCYvoBtk6VjEkMj3MWkVllxt',type:'tailieu'},
    {name:'TL: B20. Nguyên hàm và tính chất',date:'03/09',link:'https://drive.google.com/uc?export=download&id=1VDJTYRFyl_7VXM3ti7nhPh17Bz8Mmy9a',type:'tailieu'},
    {name:'TL: B21. Tích phân và tính chất',date:'10/09',link:'https://drive.google.com/uc?export=download&id=1wGjIEwCzQ16TYO7kEg5FZu7n32x5E0xN',type:'tailieu'},
    {name:'BTVN: Khoảng cách 2 ĐT',date:'14/04',link:'https://drive.google.com/drive/folders/1Nkbab9E_hESVecGJw72eTMevxVM-Blpn',type:'btvn'}
  ]},
  {id:'toan_mat_goc',name:'TOÁN MẤT GỐC-BỔ TRỢ',desc:'Toán · HSA · Bổ trợ mất gốc',icon:'fa-puzzle-piece',color:'amber',group:'hsa',lessons:[
    {name:'Đơn điệu',date:'06/08',link:'https://www.youtube.com/watch?v=2fdELuVqzEU',type:'video'},
    {name:'Song trục hàm ẩn',date:'19/08',link:'https://www.youtube.com/watch?v=iPsWb1IsG8M',type:'video'},
    {name:'Đơn điệu hàm số chứa tham số',date:'26/08',link:'https://www.youtube.com/watch?v=v7puLuDFLHI',type:'video'},
    {name:'TL: Đơn điệu',date:'06/08',link:'https://drive.google.com/uc?export=download&id=1n8UBjMJ4GuFcqx_iGbQOIbod7cy_sRIH',type:'tailieu'},
    {name:'TL: Song trục hàm ẩn',date:'19/08',link:'https://drive.google.com/uc?export=download&id=180ebAPFOfFAMk5QqSnJntT7S7yZIbKF3',type:'tailieu'},
    {name:'TL: Đơn điệu hàm số chứa tham số',date:'26/08',link:'https://drive.google.com/uc?export=download&id=1KTie5jIedaRGOPF-9y4Q0ln-eF3QGGJt',type:'tailieu'}
  ]},
  {id:'van_co_ban',name:'VĂN CƠ BẢN',desc:'Ngữ văn · HSA · Lớp 12',icon:'fa-feather-alt',color:'violet',group:'hsa',lessons:[
    {name:'Tổng quan chương trình và bt minh họa',date:'12/04',link:'https://www.youtube.com/watch?v=Z-w9VSavfms',type:'video'},
    {name:'Khái quát về từ và các vấn đề của từ Tiếng Việt',date:'19/04',link:'https://www.youtube.com/watch?v=hB-g9ln_050',type:'video'},
    {name:'Biện pháp tu từ về từ Tiếng Việt',date:'07/05',link:'https://www.youtube.com/watch?v=blxHvOEP4Ig',type:'video'},
    {name:'Biện pháp tu từ về từ Tiếng Việt -Tiếp',date:'10/05',link:'https://www.youtube.com/watch?v=a36xa_nZBCs',type:'video'},
    {name:'Khái quát tiến trình VHVN',date:'16/05',link:'https://www.youtube.com/watch?v=Y9DWFwIy8Ps',type:'video'},
    {name:'Phong cách ngôn ngữ',date:'17/05',link:'https://www.youtube.com/watch?v=eC9tqrBlvkU',type:'video'},
    {name:'Phong cách ngôn ngữ trong TV(sách)',date:'21/05',link:'https://www.youtube.com/watch?v=OcBeSVjuKC8',type:'video'},
    {name:'Khái quát tiến trình văn học VN-Tiếp',date:'23/05',link:'https://www.youtube.com/watch?v=LGPh0uWkKj4',type:'video'},
    {name:'Tổng quan về câu và những vấn để câu Tiếng Việt',date:'24/05',link:'https://www.youtube.com/watch?v=g1HLtU9v4xs',type:'video'},
    {name:'Đặc điểm của Văn học Việt Nam-Cô P',date:'30/05',link:'https://www.youtube.com/watch?v=Sr6-0HxQVFs',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ T5 - ĐỊNH TÍNH',date:'01/06',link:'https://www.youtube.com/watch?v=yoSJPBKg7EA',type:'video'},
    {name:'Văn bản nghị luận',date:'04/06',link:'https://www.youtube.com/watch?v=EGcJkMDuCM0',type:'video'},
    {name:'Đặc điểm của Văn học Việt Nam-Tiếp(Cô P)',date:'05/06',link:'https://www.youtube.com/watch?v=8Xd57zZ9F70',type:'video'},
    {name:'Các dạng câu hỏi định tính',date:'07/06',link:'https://www.youtube.com/watch?v=nS2nVqDZuCk',type:'video'},
    {name:'Đặc điểm của Văn học dân gian Việt Nam',date:'13/06',link:'https://www.youtube.com/watch?v=RxvzptgGBwA',type:'video'},
    {name:'6 Thao tác lập luận và chữa bài tập',date:'14/06',link:'https://www.youtube.com/watch?v=zzTFiVZEQ5k',type:'video'},
    {name:'Đặc điểm của Văn học dân gian Việt Nam-Tiếp',date:'20/06',link:'https://www.youtube.com/watch?v=cBCUvCly_eI',type:'video'},
    {name:'Chuyên đề đọc hiểu - Cô Huế',date:'21/06',link:'https://www.youtube.com/watch?v=7iDv0pAjupQ',type:'video'},
    {name:'Đặc điểm của Văn học trung đại Việt Nam',date:'26/06',link:'https://www.youtube.com/watch?v=xix1WsQzwAc',type:'video'},
    {name:'Cô Huế',date:'28/06',link:'https://www.youtube.com/watch?v=v15pgPofxXo',type:'video'},
    {name:'Đặc điểm Văn học trung đại VN - Tiếp',date:'04/07',link:'https://www.youtube.com/watch?v=UYxtNNSerUU',type:'video'},
    {name:'Chữa đề thi thử Định tính tháng 6 - Cô Huế',date:'05/07',link:'https://www.youtube.com/watch?v=9Dpg7tWHrx8',type:'video'},
    {name:'Luyện tập đọc VB Thơ Đường luật - Cô Phương',date:'11/07',link:'https://www.youtube.com/watch?v=06bhgipyl0s',type:'video'},
    {name:'Thơ và truyện thơ - cô Huế',date:'12/07',link:'https://www.youtube.com/watch?v=zrh8supFlMo',type:'video'},
    {name:'Luyện tập đọc VB Thơ Đường luật - Tiếp - Cô Phương',date:'18/07',link:'https://www.youtube.com/watch?v=i_HoFdrhIrg',type:'video'},
    {name:'Đọc hiểu thơ - Phong trào thơ mới - Cô Huế',date:'19/07',link:'https://www.youtube.com/watch?v=ulkMdoUd1V8',type:'video'},
    {name:'Đặc điểm Văn học hiện đại VN - Cô Phương',date:'22/07',link:'https://www.youtube.com/watch?v=TTsngvvlVL4',type:'video'},
    {name:'Đọc hiểu truyện - Khái quát một số vấn đề của truyện',date:'26/07',link:'https://www.youtube.com/watch?v=6obgoFQN5Jk',type:'video'},
    {name:'Đặc điểm Văn học hiện đại VN (Tiếp) - Cô Phương',date:'01/08',link:'https://www.youtube.com/watch?v=X9xaJxIhwg8',type:'video'},
    {name:'Đọc hiểu truyện (P2) - Các thao tác khám phá VB truyện',date:'02/08',link:'https://www.youtube.com/watch?v=L9ZnhIESz-k',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết hiện đại - Cô Phương',date:'08/08',link:'https://www.youtube.com/watch?v=EkdHcmYlmQs',type:'video'},
    {name:'Đọc hiểu truyện (P3) - Tiểu thuyết hiện đại - Cô Huế',date:'09/08',link:'https://www.youtube.com/watch?v=bjnnuUVWnkM',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết hiện đại (Tiếp)',date:'15/08',link:'https://www.youtube.com/watch?v=k4TIco0Vwzw',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ THÁNG 7',date:'17/08',link:'https://www.youtube.com/watch?v=IpIFcC1ibjo',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết Hiện thực - Cô Phương',date:'22/08',link:'https://www.youtube.com/watch?v=X6kIHu52zxo',type:'video'},
    {name:'Chữa đề thi thử Định tính tháng 7 (Tiếp) - Cô Huế',date:'23/08',link:'https://www.youtube.com/watch?v=y0wEdcOm1GU',type:'video'},
    {name:'CHỮA ĐỀ THI ĐỊNH TÍNH THÁNG 8',date:'05/09',link:'https://www.youtube.com/watch?v=T6hHaxonSBI',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết Hiện thực (Tiếp)',date:'12/09',link:'https://www.youtube.com/watch?v=Gkwcrdkyfi4',type:'video'},
    {name:'Thể loại kí - Phần 1 - Cô Huế',date:'13/09',link:'https://www.youtube.com/watch?v=7Z6PeZvTKZo',type:'video'},
    {name:'TL: Tổng quan chương trình và bt minh họa',date:'12/04',link:'https://drive.google.com/uc?export=download&id=1g7MF25cMAoMl1LgzLMzCZlF9WVoXZITT',type:'tailieu'},
    {name:'TL: Khái quát về từ và các vấn đề của từ Tiếng Việt',date:'19/04',link:'https://drive.google.com/uc?export=download&id=1fmkWhEJck7JqufzzhxBpJX8lwbp0swAe',type:'tailieu'},
    {name:'TL: Biện pháp tu từ về từ Tiếng Việt',date:'07/05',link:'https://drive.google.com/uc?export=download&id=161phZSU80T8EacOrPMfTlrr-Wizt7JUf',type:'tailieu'},
    {name:'TL: Khái quát tiến trình VHVN',date:'16/05',link:'https://drive.google.com/uc?export=download&id=1VJGBIu1ECIFB3eQM5ly4HwT2iku6Ln5r',type:'tailieu'},
    {name:'TL: Phong cách ngôn ngữ',date:'17/05',link:'https://drive.google.com/uc?export=download&id=1pUTE80dUfP0IrfCEW5En_uxubv_hlgpm',type:'tailieu'},
    {name:'TL: Phong cách ngôn ngữ trong TV(sách)',date:'21/05',link:'https://drive.google.com/uc?export=download&id=1dyn7nR2DK0icJHWjTAaU2j5SZovI7VH-',type:'tailieu'},
    {name:'TL: Tổng quan về câu và những vấn để câu Tiếng Việt',date:'24/05',link:'https://drive.google.com/uc?export=download&id=11yZdXCqmav2DZfw_Pu6jABbv74UmWltW',type:'tailieu'},
    {name:'TL: Đặc điểm của Văn học Việt Nam-Cô P',date:'30/05',link:'https://drive.google.com/uc?export=download&id=1syuCfbK_vf5lgTBFGaniwcQz-fbtqbpM',type:'tailieu'},
    {name:'TL: CHỮA ĐỀ THI THỬ T5 - ĐỊNH TÍNH',date:'01/06',link:'https://drive.google.com/uc?export=download&id=1KFF0XOvwxJKeo4kiqHdLiSjCHPb7Fp4c',type:'tailieu'},
    {name:'TL: Văn bản nghị luận',date:'04/06',link:'https://drive.google.com/uc?export=download&id=124u1H-BYbYbrfwpDTHGS_QZPIhW-ZkxX',type:'tailieu'},
    {name:'TL: Các dạng câu hỏi định tính',date:'07/06',link:'https://drive.google.com/uc?export=download&id=1DxegSl5g_M9PyWiLwNlAmr3uz5O2XmtQ',type:'tailieu'},
    {name:'TL: Đặc điểm của Văn học dân gian Việt Nam',date:'13/06',link:'https://drive.google.com/uc?export=download&id=1HqnVj5ppPjGPJYEWLbOyHN5rERnxFb7s',type:'tailieu'},
    {name:'TL: 6 Thao tác lập luận và chữa bài tập',date:'14/06',link:'https://drive.google.com/uc?export=download&id=1jGx387U_e_2rsgTKRV3SkPcUv3Q3UEMZ',type:'tailieu'},
    {name:'TL: Chuyên đề đọc hiểu - Cô Huế',date:'21/06',link:'https://drive.google.com/uc?export=download&id=1Q-A6E5gMjGM8_VY3OfyHWgk7FP-lvGNh',type:'tailieu'},
    {name:'TL: Đặc điểm Văn học trung đại Việt Nam',date:'26/06',link:'https://drive.google.com/uc?export=download&id=1HFIbJTvWnUEGo232c-ByS6AkQFK7FprV',type:'tailieu'},
    {name:'TL: Chữa đề thi thử Định tính tháng 6 - Cô Huế',date:'05/07',link:'https://drive.google.com/uc?export=download&id=1lzuVIaFthc6L51cXHvuKBrZ-rQXjO7Va',type:'tailieu'},
    {name:'TL: Luyện tập đọc VB Thơ Đường luật',date:'11/07',link:'https://drive.google.com/uc?export=download&id=1s6PdB3R_xT9Df4wivWmxIRTGCwyc5_18',type:'tailieu'},
    {name:'TL: Thơ và truyện thơ - cô Huế',date:'12/07',link:'https://drive.google.com/uc?export=download&id=1A759D2LavUdYyW9G9pPdVrpARBfnn0ld',type:'tailieu'},
    {name:'TL: Đọc hiểu thơ - Phong trào thơ mới',date:'19/07',link:'https://drive.google.com/uc?export=download&id=1DUVQtjF0FFZIaWqTGXf76XeTxV6YuJnt',type:'tailieu'},
    {name:'TL: Đặc điểm Văn học hiện đại VN - Cô Phương',date:'22/07',link:'https://drive.google.com/uc?export=download&id=1UX-awVX0TxRNQNGj9NDY9Q8d_zqTJEX_',type:'tailieu'},
    {name:'TL: Đọc hiểu truyện - Khái quát vấn đề của truyện',date:'26/07',link:'https://drive.google.com/uc?export=download&id=1Zwwn-eHkklQFxi8gEiSIEDY0kOpNp4Fs',type:'tailieu'},
    {name:'TL: Đọc hiểu truyện (P2) - Các thao tác khám phá VB',date:'02/08',link:'https://drive.google.com/uc?export=download&id=1JBpolU-V8YbR6xmuH9jumdg7xlNQaQ1T',type:'tailieu'},
    {name:'TL: Luyện đọc truyện ngắn, tiểu thuyết hiện đại',date:'08/08',link:'https://drive.google.com/uc?export=download&id=1Y3rgt4cSzxtOMW6a-0QSK9Rc0OVRn2Au',type:'tailieu'},
    {name:'TL: Đọc hiểu truyện (P3) - Tiểu thuyết hiện đại',date:'09/08',link:'https://drive.google.com/uc?export=download&id=1HvLkToWjZDmCBpDTBzak99ptCZdNxZVD',type:'tailieu'},
    {name:'TL: CHỮA ĐỀ THI THỬ THÁNG 7',date:'17/08',link:'https://drive.google.com/uc?export=download&id=1tBh0zQCSzVtLgIrktfN6BRHOsR4Z8XUJ',type:'tailieu'},
    {name:'TL: Luyện đọc truyện ngắn, tiểu thuyết Hiện thực',date:'22/08',link:'https://drive.google.com/uc?export=download&id=1YKwUvL4Wu6WQaNVRZzGoDCstaRTw50NN',type:'tailieu'},
    {name:'TL: CHỮA ĐỀ THI ĐỊNH TÍNH THÁNG 8',date:'05/09',link:'https://drive.google.com/uc?export=download&id=1H7RITtz4vCJfZ1K-cfjAow2-qxT1yxSi',type:'tailieu'},
    {name:'TL: Thể loại kí - Phần 1 - Cô Huế',date:'13/09',link:'https://drive.google.com/uc?export=download&id=1ybpN0EXukw4zJSinV_VHhDANRM_gZY3-',type:'tailieu'}
  ]},
  {id:'van_nang_cao',name:'VĂN NÂNG CAO',desc:'Ngữ văn · HSA · Nâng cao',icon:'fa-star',color:'violet',group:'hsa',lessons:[
    {name:'Khái quát về từ và các vấn đề của từ Tiếng Việt',date:'15/04',link:'https://www.youtube.com/watch?v=LrL8Z9stsvM',type:'video'},
    {name:'Câu Tiếng Việt',date:'22/04',link:'https://www.youtube.com/watch?v=FX3aQFeojqk',type:'video'},
    {name:'Biện pháp tu từ',date:'29/04',link:'https://www.youtube.com/watch?v=ygep-A-D9dw',type:'video'},
    {name:'Phong cách ngôn ngữ',date:'06/05',link:'https://www.youtube.com/watch?v=vqaFN4nKdtg',type:'video'},
    {name:'Phong cách ngôn ngữ - Tiếp',date:'13/05',link:'https://www.youtube.com/watch?v=55QW7eGf0Dg',type:'video'},
    {name:'Khái quát tiến trình văn học VN',date:'17/05',link:'https://www.youtube.com/watch?v=8KPwGpOoYM4',type:'video'},
    {name:'Các dạng câu hỏi định tính',date:'20/05',link:'https://www.youtube.com/watch?v=8hEflqI8CuU',type:'video'},
    {name:'Khái quát tiến trình văn học VN-Tiếp',date:'24/05',link:'https://www.youtube.com/watch?v=hyrGPSybEqo',type:'video'},
    {name:'Các dạng câu hỏi định tính(Tiếp)',date:'27/05',link:'https://www.youtube.com/watch?v=z2E90skw1tM',type:'video'},
    {name:'Đặc điểm chung của văn học Việt Nam-Cô P',date:'31/05',link:'https://www.youtube.com/watch?v=AcHwP_9a60Q',type:'video'},
    {name:'Văn bản nghị luận',date:'03/06',link:'https://www.youtube.com/watch?v=eAEZzZHkIYQ',type:'video'},
    {name:'Đặc điểm của văn học Việt Nam-Tiếp',date:'04/06',link:'https://www.youtube.com/watch?v=SGBzvU3FRDM',type:'video'},
    {name:'6 Thao tác lập luận và chữa bài tập',date:'10/06',link:'https://www.youtube.com/watch?v=yvvoeliIFoY',type:'video'},
    {name:'Đặc điểm của Văn học dân gian Việt Nam',date:'14/06',link:'https://www.youtube.com/watch?v=XjWRf_eeVXU',type:'video'},
    {name:'Chuyên đề đọc hiểu - Cô Huế',date:'17/06',link:'https://www.youtube.com/watch?v=4WjCE2j99Mg',type:'video'},
    {name:'Đặc điểm của Văn học dân gian Việt Nam-Tiếp',date:'21/06',link:'https://www.youtube.com/watch?v=nzUWw6pMprc',type:'video'},
    {name:'Đặc điểm của Văn học trung đại Việt Nam',date:'25/06',link:'https://www.youtube.com/watch?v=q37nPLcutHE',type:'video'},
    {name:'Chuyên đề đọc hiểu - Tiếp - Cô Huế',date:'26/06',link:'https://www.youtube.com/watch?v=HnIegSVxtMc',type:'video'},
    {name:'Đọc hiểu thơ - Cô Huế',date:'01/07',link:'https://www.youtube.com/watch?v=9zNRVEB9Z84',type:'video'},
    {name:'Đặc điểm Văn học trung đại VN - Tiếp',date:'05/07',link:'https://www.youtube.com/watch?v=AcuvxHNhEoI',type:'video'},
    {name:'Chữa đề thi thử Định tính tháng 6 - Cô Huế',date:'05/07',link:'https://www.youtube.com/watch?v=9Dpg7tWHrx8',type:'video'},
    {name:'Thơ và truyện thơ - Cô Huế',date:'08/07',link:'https://www.youtube.com/watch?v=TGQWcW4xMiY',type:'video'},
    {name:'Luyện tập đọc VB Thơ Đường luật',date:'12/07',link:'https://www.youtube.com/watch?v=_frGadKB6e8',type:'video'},
    {name:'Đọc hiểu thơ - Phong trào thơ mới - Cô Huế',date:'15/07',link:'https://www.youtube.com/watch?v=Y5DVFmpI7kQ',type:'video'},
    {name:'Luyện tập đọc VB Thơ Đường luật - Tiếp - Cô Phương',date:'19/07',link:'https://www.youtube.com/watch?v=eaqhCacUs3E',type:'video'},
    {name:'Đặc điểm Văn học Hiện đại VN - Cô Phương',date:'20/07',link:'https://www.youtube.com/watch?v=5c05UYBEO2o',type:'video'},
    {name:'Đọc hiểu truyện - Khái quát vấn đề của truyện - Cô Huế',date:'22/07',link:'https://www.youtube.com/watch?v=RpTRD4dRgg8',type:'video'},
    {name:'Đặc điểm Văn học hiện đại VN (Tiếp) - Cô Phương',date:'02/08',link:'https://www.youtube.com/watch?v=9hNzfn34qzs',type:'video'},
    {name:'Đọc hiểu truyện - Tiểu thuyết hiện đại - Cô Huế',date:'05/08',link:'https://www.youtube.com/watch?v=k8j15kRlVYE',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết hiện đại - Cô Phương',date:'09/08',link:'https://www.youtube.com/watch?v=NSYagOlEMS0',type:'video'},
    {name:'Đọc hiểu truyện - Tiểu thuyết hiện đại (Tiếp) - Cô Huế',date:'12/08',link:'https://www.youtube.com/watch?v=0XQ0pDmYQss',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết hiện đại (Tiếp)',date:'16/08',link:'https://www.youtube.com/watch?v=LN00hFIRMHA',type:'video'},
    {name:'Chữa đề thi thử Định tính tháng 7 - Cô Huế',date:'19/08',link:'https://www.youtube.com/watch?v=w7vP56o7-mo',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết Hiện thực - Cô Phương',date:'23/08',link:'https://www.youtube.com/watch?v=CooeLYxlr5c',type:'video'},
    {name:'Truyện Trung đại (Truyện truyền kì)+Truyện dân gian - Cô Huế',date:'26/08',link:'https://www.youtube.com/watch?v=Zr0JEzbJ4sw',type:'video'},
    {name:'Thể loại kí - Phần 1 - Cô Huế',date:'09/09',link:'https://www.youtube.com/watch?v=p5xRA4JGz1g',type:'video'},
    {name:'Luyện đọc truyện ngắn, tiểu thuyết Hiện thực (Tiếp)',date:'13/09',link:'https://www.youtube.com/watch?v=GY5r_t4M6_w',type:'video'},
    {name:'TL: Khái quát về từ và các vấn đề của từ Tiếng Việt',date:'15/04',link:'https://drive.google.com/uc?export=download&id=1T8_KrwdAlTMWUwHQDFOBa6CaPqsiYJKz',type:'tailieu'},
    {name:'TL: Câu Tiếng Việt',date:'22/04',link:'https://drive.google.com/uc?export=download&id=11yZdXCqmav2DZfw_Pu6jABbv74UmWltW',type:'tailieu'},
    {name:'TL: Phong cách ngôn ngữ',date:'06/05',link:'https://drive.google.com/uc?export=download&id=137cHEN1z-knMgR2-Kaii3larb1mbS1si',type:'tailieu'},
    {name:'TL: Khái quát tiến trình văn học VN',date:'17/05',link:'https://drive.google.com/uc?export=download&id=1uIO2yVvjsThO3vjbKNxGKOaLIcDItOCo',type:'tailieu'},
    {name:'TL: Các dạng câu hỏi định tính',date:'20/05',link:'https://drive.google.com/uc?export=download&id=1LaOj_qSe9zd7XFPoDIVpm8kLyvWW4oHz',type:'tailieu'},
    {name:'TL: Đặc điểm chung của văn học Việt Nam-Cô P',date:'31/05',link:'https://drive.google.com/uc?export=download&id=1YFgwFryfb5A7iRN9XwEoRFsRqUlU_qpt',type:'tailieu'},
    {name:'TL: Văn bản nghị luận',date:'03/06',link:'https://drive.google.com/uc?export=download&id=1ey56G5woU2s-Q9Oy3xcRQz_Vp6SxTBt3',type:'tailieu'},
    {name:'TL: 6 Thao tác lập luận và chữa bài tập',date:'10/06',link:'https://drive.google.com/uc?export=download&id=1QkxLqM8orM-goVnUQwIeMqO8TaCQ4Cna',type:'tailieu'},
    {name:'TL: Đặc điểm của Văn học dân gian Việt Nam',date:'14/06',link:'https://drive.google.com/uc?export=download&id=1tEk7GskcPpM8oNEMiMSdu4DfjoVniFRh',type:'tailieu'},
    {name:'TL: Chuyên đề đọc hiểu - Cô Huế',date:'17/06',link:'https://drive.google.com/uc?export=download&id=1KoJcOxDJr5SOc6_ccs8k7kj1LrvoueKo',type:'tailieu'},
    {name:'TL: Đặc điểm Văn học trung đại Việt Nam',date:'25/06',link:'https://drive.google.com/uc?export=download&id=18pc9Qu8kbDyn_lofr-X3XsXNG31Ton-0',type:'tailieu'},
    {name:'TL: Đọc hiểu thơ - Cô Huế',date:'01/07',link:'https://drive.google.com/uc?export=download&id=1e8e_s-QnUbRIy5VblvrTlpO9D5BZNPwG',type:'tailieu'},
    {name:'TL: Chữa đề thi thử Định tính tháng 6 - Cô Huế',date:'05/07',link:'https://drive.google.com/uc?export=download&id=1lzuVIaFthc6L51cXHvuKBrZ-rQXjO7Va',type:'tailieu'},
    {name:'TL: Thơ và truyện thơ - Cô Huế',date:'08/07',link:'https://drive.google.com/uc?export=download&id=1dVqiQqjRHCYsxg2hEzWNQaZjkhFx8-Rb',type:'tailieu'},
    {name:'TL: Luyện tập đọc VB Thơ Đường luật',date:'12/07',link:'https://drive.google.com/uc?export=download&id=1qqksrnggpuutSlRIXaRQ7bm1rV7Qv4Yw',type:'tailieu'},
    {name:'TL: Đọc hiểu thơ - Phong trào thơ mới - Cô Huế',date:'15/07',link:'https://drive.google.com/uc?export=download&id=11CSERjnH-P9io1owIuMSO0_wX6H0NrzI',type:'tailieu'},
    {name:'TL: Đặc điểm Văn học Hiện đại VN - Cô Phương',date:'20/07',link:'https://drive.google.com/uc?export=download&id=1HWc8b3Mk9oHFB6DR9ymAyOLkVM2HjbSg',type:'tailieu'},
    {name:'TL: Đọc hiểu truyện - Khái quát vấn đề của truyện',date:'22/07',link:'https://drive.google.com/uc?export=download&id=1LcMPDK4nrqJI7liq9QJair8WOaWVrcPc',type:'tailieu'},
    {name:'TL: Đọc hiểu truyện - Tiểu thuyết hiện đại - Cô Huế',date:'05/08',link:'https://drive.google.com/uc?export=download&id=1Mqo8aV3ICHIi8bz2VKpB1WsjdeO0Z5ty',type:'tailieu'},
    {name:'TL: Luyện đọc truyện ngắn, tiểu thuyết hiện đại',date:'09/08',link:'https://drive.google.com/uc?export=download&id=1Lb_LwRWnyyJv79VBwQzvWwUe57qXqZQ9',type:'tailieu'},
    {name:'TL: Chữa đề thi thử Định tính tháng 7 - Cô Huế',date:'19/08',link:'https://drive.google.com/uc?export=download&id=1Ir-YcWDjo0bLAAJ29_p-KW6VDZvNMivM',type:'tailieu'},
    {name:'TL: Luyện đọc truyện ngắn, tiểu thuyết Hiện thực',date:'23/08',link:'https://drive.google.com/uc?export=download&id=18pPEBkW7VahNe080a2MaoF71oT5GZV_O',type:'tailieu'},
    {name:'TL: Truyện Trung đại + Truyện dân gian - Cô Huế',date:'26/08',link:'https://drive.google.com/uc?export=download&id=1RCDkU2BIgOqgXdNvFmozdvVJa42_HdPi',type:'tailieu'},
    {name:'TL: Thể loại kí - Phần 1 - Cô Huế',date:'09/09',link:'https://drive.google.com/uc?export=download&id=1-Srcm8jnlwR-3G_tgbaFn9t7zRqPMUwR',type:'tailieu'}
  ]},
  {id:'tieng_anh',name:'TIẾNG ANH',desc:'Tiếng Anh · HSA · Lớp 12',icon:'fa-language',color:'amber',group:'hsa',lessons:[
    {name:'Thì ĐT ( Đơn, Tiếp Diễn)',date:'09/04',link:'https://www.youtube.com/watch?v=ctgcJ5Ig4w8',type:'video'},
    {name:'Vocab : Sports, Healthy & Lifestyle',date:'15/04',link:'https://www.youtube.com/watch?v=UX8jskaVvoE',type:'video'},
    {name:'Vocab : Sports, Healthy & Lifestyle',date:'22/04',link:'https://www.youtube.com/watch?v=0m-yB6YitWg',type:'video'},
    {name:'Chữa BTVN Vocab : Sports, Healthy & Lifestyle',date:'06/05',link:'https://www.youtube.com/watch?v=cvhbVrUTEQs',type:'video'},
    {name:'Thì ĐT ( Tiếp Diễn, Hoàn thành)',date:'13/05',link:'https://www.youtube.com/watch?v=fQ7HdUGHdYw',type:'video'},
    {name:'Vocab: Travel& Tourism',date:'17/05',link:'https://www.youtube.com/watch?v=GixszVOzSJ4',type:'video'},
    {name:'Thì HTTD, TLTĐ - Thì hoàn thành',date:'20/05',link:'https://www.youtube.com/watch?v=XtbtsHf08fM',type:'video'},
    {name:'Vocab: Travel& Tourism',date:'22/05',link:'https://www.youtube.com/watch?v=z-OUzQ5EidY',type:'video'},
    {name:'Thì ĐT (QKHT-TLHT - Thì HTTD)',date:'27/05',link:'https://www.youtube.com/watch?v=GBs5S_fAFA4',type:'video'},
    {name:'Vocab: Travel& Tourism - Tiếp',date:'31/05',link:'https://www.youtube.com/watch?v=32vUKhzDf-k',type:'video'},
    {name:'Thì Hoàn thành tiếp diễn',date:'03/06',link:'https://www.youtube.com/watch?v=2UU5p0hmBZQ',type:'video'},
    {name:'Vocab: Environment and Sustainable development',date:'07/06',link:'https://www.youtube.com/watch?v=sYJ1LHZTvqU',type:'video'},
    {name:'Chữa BTVN Sự phối hợp thì',date:'10/06',link:'https://www.youtube.com/watch?v=6PS8aWYxmzs',type:'video'},
    {name:'Vocab: Environment and Sustainable development - Tiếp',date:'14/06',link:'https://www.youtube.com/watch?v=iiLUe-ZUZPA',type:'video'},
    {name:'Chữa BTVN Sự phối hợp thì-Tiếp',date:'17/06',link:'https://www.youtube.com/watch?v=BP-R1BJxu2Q',type:'video'},
    {name:'Vocab: Environment and Sustainable development - Tiếp',date:'21/06',link:'https://www.youtube.com/watch?v=RbtplYHJEj8',type:'video'},
    {name:'Sự phối hợp thì - Tiếp',date:'24/06',link:'https://www.youtube.com/watch?v=cJ_W-wOvJHg',type:'video'},
    {name:'Vocab: Topic Education',date:'28/06',link:'https://www.youtube.com/watch?v=bM_cj3TzVtE',type:'video'},
    {name:'Sự hoà hợp Chủ ngữ - Động từ',date:'01/07',link:'https://www.youtube.com/watch?v=3aWdlDYf-Qg',type:'video'},
    {name:'Vocab: Topic Education - Tiếp',date:'05/07',link:'https://www.youtube.com/watch?v=zUe9s7Pl5yQ',type:'video'},
    {name:'Sự hoà hợp Chủ ngữ - Động từ - Tiếp',date:'08/07',link:'https://www.youtube.com/watch?v=96MV6ZpN9t4',type:'video'},
    {name:'Vocab: Topic Education - Tiếp',date:'12/07',link:'https://www.youtube.com/watch?v=EIFujSreZGo',type:'video'},
    {name:'Sự hoà hợp Chủ ngữ - Động từ - Tiếp',date:'15/07',link:'https://www.youtube.com/watch?v=X_aGX3FNxoE',type:'video'},
    {name:'Vocab (5): Science and technology',date:'19/07',link:'https://www.youtube.com/watch?v=PDAnkyY4K18',type:'video'},
    {name:'Modal verbs (Động từ khuyết thiếu)',date:'22/07',link:'https://www.youtube.com/watch?v=gZuUDItZWP4',type:'video'},
    {name:'Vocab (5): Science and technology - Tiếp',date:'26/07',link:'https://www.youtube.com/watch?v=xG8_l8j5PZI',type:'video'},
    {name:'Modal verbs (Động từ khuyết thiếu) - Tiếp',date:'29/07',link:'https://www.youtube.com/watch?v=7D9m5z83MhE',type:'video'},
    {name:'Word formation (Cách thành lập từ)',date:'02/08',link:'https://www.youtube.com/watch?v=_bgR_VlKFnQ',type:'video'},
    {name:'Câu bị động',date:'05/08',link:'https://www.youtube.com/watch?v=BnwCJvc8hlA',type:'video'},
    {name:'Word formation (Cách thành lập từ) - Tiếp',date:'09/08',link:'https://www.youtube.com/watch?v=QXqmJZzBc2w',type:'video'},
    {name:'Câu bị động - Tiếp',date:'12/08',link:'https://www.youtube.com/watch?v=Gi9aW5atG-U',type:'video'},
    {name:'Chữa BTVN Word formation (Cách thành lập từ)',date:'16/08',link:'https://www.youtube.com/watch?v=PhJCJ23Xqko',type:'video'},
    {name:'Câu bị động (Passive voice)',date:'19/08',link:'https://www.youtube.com/watch?v=TWX9jGYMsCE',type:'video'},
    {name:'Vocab (6): Work and Employment',date:'23/08',link:'https://www.youtube.com/watch?v=_B9rcQOqkWk',type:'video'},
    {name:'Reported speech',date:'26/08',link:'https://www.youtube.com/watch?v=3_vTGZy6vt4',type:'video'},
    {name:'CHỮA ĐỀ THI TIẾNG ANH THÁNG 8',date:'06/09',link:'https://www.youtube.com/watch?v=BqmDlhMpsvY',type:'video'},
    {name:'Reported speech - Tiếp',date:'09/09',link:'https://www.youtube.com/watch?v=c9MswOXY8lA',type:'video'},
    {name:'Vocab (6): Work and Employment - Tiếp',date:'13/09',link:'https://www.youtube.com/watch?v=VefKmQvIats',type:'video'},
    {name:'TL: Thì ĐT ( Đơn, Tiếp Diễn)',date:'09/04',link:'https://drive.google.com/uc?export=download&id=1q1b3Bjf1Vx1S21LDWVdASy7pRiousgn2',type:'tailieu'},
    {name:'TL: Vocab : Sports, Healthy & Lifestyle',date:'15/04',link:'https://drive.google.com/uc?export=download&id=1NGuqWRJonhA0nojqeASscmQ3X5URD0Le',type:'tailieu'},
    {name:'TL: Vocab : Sports, Healthy & Lifestyle',date:'22/04',link:'https://drive.google.com/uc?export=download&id=1jM7sg42dBksPBNr--sudrcSQsR3ldYqZ',type:'tailieu'},
    {name:'TL: Thì ĐT ( Tiếp Diễn, Hoàn thành)',date:'13/05',link:'https://drive.google.com/uc?export=download&id=1XfX8NHaer7mlbMXVZd7_G4TnZ7v2gSOA',type:'tailieu'},
    {name:'TL: Vocab: Travel& Tourism',date:'17/05',link:'https://drive.google.com/uc?export=download&id=1iD78VtY1UVnyMflFH8YyD7fsOzH9PN0H',type:'tailieu'},
    {name:'TL: Thì HTTD, TLTĐ - Thì hoàn thành',date:'20/05',link:'https://drive.google.com/uc?export=download&id=1OiyC_6V5ZybbeoJR4W4UIyMKIIeyo9tF',type:'tailieu'},
    {name:'TL: Thì ĐT (QKHT-TLHT - Thì HTTD)',date:'27/05',link:'https://drive.google.com/uc?export=download&id=1XX6Jhtg0dPt3v_dbre74P6bebtGk641a',type:'tailieu'},
    {name:'TL: Thì Hoàn thành tiếp diễn',date:'03/06',link:'https://drive.google.com/uc?export=download&id=1SJdLPt7WtcyuPi1wWTuzyykLxlNDMnqt',type:'tailieu'},
    {name:'TL: Vocab: Environment and Sustainable development',date:'07/06',link:'https://drive.google.com/uc?export=download&id=1dZRDZ2zDhGTETHUI4ri1ReYWzc0hBfdi',type:'tailieu'},
    {name:'TL: Chữa BTVN Sự phối hợp thì',date:'10/06',link:'https://drive.google.com/uc?export=download&id=186dmWmuFIJ3Lir_9R9PymvpCglV5fCZ_',type:'tailieu'},
    {name:'TL: Vocab: Topic Education',date:'28/06',link:'https://drive.google.com/uc?export=download&id=1F9SZ1b98hX7y7V4LBkqSvx3PxJcRxWoG',type:'tailieu'},
    {name:'TL: Sự hoà hợp Chủ ngữ - Động từ',date:'01/07',link:'https://drive.google.com/uc?export=download&id=1VqE7tPbRBqBRjo7xLJADdZCJwU0F3_aj',type:'tailieu'},
    {name:'TL: Vocab (5): Science and technology',date:'19/07',link:'https://drive.google.com/uc?export=download&id=1mEKN3npgj4-EQB2GDu_YkSnT73UwPbOJ',type:'tailieu'},
    {name:'TL: Modal verbs (Động từ khuyết thiếu)',date:'22/07',link:'https://drive.google.com/uc?export=download&id=1F0TpK0T4fOCBDPA_J6O2OjLQ5kZ5ysT8',type:'tailieu'},
    {name:'TL: Word formation (Cách thành lập từ)',date:'02/08',link:'https://drive.google.com/uc?export=download&id=1WlRTso-9xN042GdC2NViT5J60WMAt25C',type:'tailieu'},
    {name:'TL: Câu bị động',date:'05/08',link:'https://drive.google.com/uc?export=download&id=1vo66P-aDe480DN908XMkgwQVxWKGH6lR',type:'tailieu'},
    {name:'TL: Chữa BTVN Word formation',date:'16/08',link:'https://drive.google.com/uc?export=download&id=1hWjREk31DngncpRRb-hkrR6iWzW0ualM',type:'tailieu'},
    {name:'TL: Vocab (6): Work and Employment',date:'23/08',link:'https://drive.google.com/uc?export=download&id=1NxZhhgaVL0_T97d7MtEYiWAZneDkOKoQ',type:'tailieu'},
    {name:'TL: Reported speech',date:'26/08',link:'https://drive.google.com/uc?export=download&id=1ZqFe8_6n1zbpx_r5egaHVFK44J0z2k4n',type:'tailieu'}
  ]},
  {id:'vat_ly',name:'VẬT LÝ',desc:'Vật lý · HSA · Lớp 12',icon:'fa-atom',color:'green',group:'hsa',lessons:[
    {name:'Động học chất điểm',date:'02/07',link:'https://www.youtube.com/watch?v=ibliEnzO2WM',type:'video'},
    {name:'Động học chất điểm - Tiếp',date:'13/07',link:'https://www.youtube.com/watch?v=TZCOVCtXPTg',type:'video'},
    {name:'Động học chất điểm - Bài toán tính tốc độ TB, tính vận tốc TB - Tiếp',date:'16/07',link:'https://www.youtube.com/watch?v=IMcjB8PR15g',type:'video'},
    {name:'Động học chất điểm - Tiếp',date:'23/07',link:'https://www.youtube.com/watch?v=vNIQV725_Cs',type:'video'},
    {name:'Rơi tự do',date:'06/08',link:'https://www.youtube.com/watch?v=TeDiQvXadzg',type:'video'},
    {name:'Rơi tự do - Tiếp',date:'12/08',link:'https://www.youtube.com/watch?v=RDjefjKbkCE',type:'video'},
    {name:'Động lực học chất điểm',date:'13/08',link:'https://www.youtube.com/watch?v=7WGeVkzR3Z0',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'20/08',link:'https://www.youtube.com/watch?v=_ibgvhvJ5S8',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'03/09',link:'https://www.youtube.com/watch?v=YTMA49sZgzM',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'10/09',link:'https://www.youtube.com/watch?v=eK67If5X1AE',type:'video'}
  ]},
  {id:'hoa_hoc',name:'HOÁ HỌC',desc:'Hoá học · HSA · Lớp 12',icon:'fa-flask',color:'amber',group:'hsa',lessons:[
    {name:'Ester lipid',date:'04/07',link:'https://www.youtube.com/watch?v=m3x1-W1V2Hc',type:'video'},
    {name:'Xà phòng',date:'16/07',link:'https://www.youtube.com/watch?v=SPaQ4U_wEA8',type:'video'},
    {name:'Luyện Tập ester lipid',date:'18/07',link:'https://www.youtube.com/watch?v=ZqcJ1GG_hZM',type:'video'},
    {name:'Carbohydrate',date:'25/07',link:'https://www.youtube.com/watch?v=BI2brc000g4',type:'video'},
    {name:'Carbohydrate (Tiếp) - Tinh bột và Cellulose',date:'31/07',link:'https://www.youtube.com/watch?v=VSZK3iyDgls',type:'video'},
    {name:'Amine',date:'07/08',link:'https://www.youtube.com/watch?v=Wtxl70xV-bY',type:'video'},
    {name:'Amino acid',date:'11/08',link:'https://www.youtube.com/watch?v=ZD5SO9CMWU8',type:'video'},
    {name:'Peptide Protein',date:'15/08',link:'https://www.youtube.com/watch?v=d6AYWcWDwl0',type:'video'},
    {name:'Luyện tập hợp chất hữu cơ chứa Nitrogen',date:'18/08',link:'https://www.youtube.com/watch?v=GGT0MivfMzE',type:'video'},
    {name:'Đại cương Polymer',date:'21/08',link:'https://www.youtube.com/watch?v=kQFU4jyMELw',type:'video'},
    {name:'Vật liệu Polymer',date:'25/08',link:'https://www.youtube.com/watch?v=Wvlq86u_HQs',type:'video'},
    {name:'Luyện tập Polymer',date:'28/08',link:'https://www.youtube.com/watch?v=XhuEzsFyhxY',type:'video'},
    {name:'Thế điện cực và nguồn điện hoá học',date:'08/09',link:'https://www.youtube.com/watch?v=Wi7SToBoZk4',type:'video'},
    {name:'Điện phân',date:'11/09',link:'https://www.youtube.com/watch?v=kC7IX2XB5ms',type:'video'}
  ]},
  {id:'sinh_hoc',name:'SINH HỌC',desc:'Sinh học · HSA · Lớp 12',icon:'fa-dna',color:'green',group:'hsa',lessons:[
    {name:'Ôn tập di truyền phân tử (P1)',date:'29/06',link:'https://www.youtube.com/watch?v=NE0uuL60kdA',type:'video'},
    {name:'Ôn tập di truyền phân tử (P1)-Tiếp',date:'06/07',link:'https://www.youtube.com/watch?v=v4n7w_QAty0',type:'video'},
    {name:'Ôn tập di truyền phân tử (P2)',date:'13/07',link:'https://www.youtube.com/watch?v=FA5fEpxUoxU',type:'video'},
    {name:'Ôn tập di truyền phân tử (P2)-Tiếp',date:'20/07',link:'https://www.youtube.com/watch?v=0MOjGoJA-rU',type:'video'},
    {name:'Ôn tập di truyền phân tử (P3)',date:'27/07',link:'https://www.youtube.com/watch?v=QdY4WPDWDaQ',type:'video'},
    {name:'Ôn tập di truyền phân tử (P3)-Tiếp',date:'03/08',link:'https://www.youtube.com/watch?v=M_Fewkn1tgA',type:'video'},
    {name:'Tổng ôn di truyền nhiễm sắc thể',date:'10/08',link:'https://www.youtube.com/watch?v=vjO-GnXttls',type:'video'},
    {name:'Tổng ôn di truyền nhiễm sắc thể-Tiếp',date:'17/08',link:'https://www.youtube.com/watch?v=zs7OcqSWGCM',type:'video'},
    {name:'Tổng ôn quy luật di truyền (P1)',date:'24/08',link:'https://www.youtube.com/watch?v=2Nc-8IIx9HA',type:'video'},
    {name:'Chữa BT Di truyền NST+Quy luật di truyền',date:'07/09',link:'https://www.youtube.com/watch?v=x5KKzcys1bs',type:'video'},
    {name:'Tổng ôn quy luật di truyền (P2)',date:'14/09',link:'https://www.youtube.com/watch?v=mr-gY4X5FEA',type:'video'}
  ]},
  {id:'lich_su',name:'LỊCH SỬ (HSA)',desc:'Lịch sử · HSA · Lớp 12',icon:'fa-landmark',color:'violet',group:'hsa',lessons:[
    {name:'Liên Hợp Quốc',date:'03/07',link:'https://www.youtube.com/watch?v=OWs24pIJsYI',type:'video'},
    {name:'Trật tự thế giới trong Chiến tranh lạnh',date:'10/07',link:'https://www.youtube.com/watch?v=n_MQrIOIYDM',type:'video'},
    {name:'Trật tự thế giới sau Chiến tranh lạnh',date:'17/07',link:'https://www.youtube.com/watch?v=6vp3TMaV-r0',type:'video'},
    {name:'Tổng ôn chủ đề 1',date:'01/08',link:'https://www.youtube.com/watch?v=p1JFoOgW8-8',type:'video'},
    {name:'Sự ra đời của Asean',date:'08/08',link:'https://www.youtube.com/watch?v=G8l13tpwgMg',type:'video'},
    {name:'Cộng đồng Asean',date:'14/08',link:'https://www.youtube.com/watch?v=y6V8NrhhNuo',type:'video'},
    {name:'Luyện đề Asean',date:'22/08',link:'https://www.youtube.com/watch?v=DT-8E7DE_CA',type:'video'},
    {name:'Cách mạng tháng 8',date:'26/08',link:'https://www.youtube.com/watch?v=dQB3swcF90I',type:'video'},
    {name:'Kháng chiến chống Pháp',date:'12/09',link:'https://www.youtube.com/watch?v=9-qQqTM8AGE',type:'video'}
  ]},
  {id:'dia_ly',name:'ĐỊA LÝ',desc:'Địa lý · HSA · Lớp 12',icon:'fa-globe-asia',color:'green',group:'hsa',lessons:[
    {name:'Vị trí địa lí và khí hậu',date:'30/06',link:'https://www.youtube.com/watch?v=-M2ZMjgmqHA',type:'video'},
    {name:'Vị trí địa lí và khí hậu - Tiếp',date:'07/07',link:'https://www.youtube.com/watch?v=DebZcz8mWtI',type:'video'},
    {name:'Đặc điểm của thiên nhiên Việt Nam',date:'14/07',link:'https://www.youtube.com/watch?v=t9y4Agvul90',type:'video'},
    {name:'Sự phân hoá đa dạng của thiên nhiên',date:'21/07',link:'https://www.youtube.com/watch?v=985mMNNzHog',type:'video'},
    {name:'Thiên nhiên theo độ cao',date:'28/07',link:'https://www.youtube.com/watch?v=uAyR8tspGu0',type:'video'},
    {name:'Tổng ôn Tự nhiên VN+CT nhiệt độ lượng mưa',date:'04/08',link:'https://www.youtube.com/watch?v=bp9L_o5UDvU',type:'video'},
    {name:'Chữa BT CT tính nhiệt độ lượng mưa+KC biển',date:'11/08',link:'https://www.youtube.com/watch?v=WjdxOl9POKk',type:'video'},
    {name:'Dân số và lao động',date:'18/08',link:'https://www.youtube.com/watch?v=e-pp-h82NOQ',type:'video'},
    {name:'Dân số và lao động - Tiếp',date:'25/08',link:'https://www.youtube.com/watch?v=Z-Xs4VegGGU',type:'video'},
    {name:'Công thức tính toán Địa lý Dân cư - Lao động',date:'08/09',link:'https://www.youtube.com/watch?v=dP-Bg3E4ScU',type:'video'}
  ]}
];

/* ============================================================
   SGK
   ============================================================ */
const SGK_SUBJECTS = [
  {id:'sgk_toan',name:'SGK TOÁN',desc:'Sách giáo khoa · Video bài giảng',icon:'fa-square-root-alt',color:'green',group:'sgk',lessons:[
    {name:'Bài 1: TÍNH ĐƠN ĐIỆU',date:'SGK',link:'https://www.youtube.com/watch?v=vqkvTdGX5c8',type:'video'},
    {name:'Bài 2: TÍNH ĐƠN ĐIỆU - P2',date:'SGK',link:'https://www.youtube.com/watch?v=G5NXZbxmM-A',type:'video'},
    {name:'Bài 3: CỰC TRỊ CỦA HÀM SỐ',date:'SGK',link:'https://www.youtube.com/watch?v=Z_9UpGK991M',type:'video'},
    {name:'Bài 4: CỰC TRỊ HÀM SỐ - P2',date:'SGK',link:'https://www.youtube.com/watch?v=40WVbV3G540',type:'video'},
    {name:'Bài 5: GTLN - GTNN CỦA HÀM SỐ',date:'SGK',link:'https://www.youtube.com/watch?v=qCKviOxmmeE',type:'video'},
    {name:'Bài 1.1: VECTO TƯƠNG KHÔNG GIAN (P1)',date:'SGK',link:'https://www.youtube.com/watch?v=OA3vVKt71zM',type:'video'},
    {name:'Bài 1.2: VECTO TRONG KHÔNG GIAN (P2)',date:'SGK',link:'https://www.youtube.com/watch?v=Qh4UjgpfA1U',type:'video'},
    {name:'Bài 2: VECTƠ VÀ CÁC PHÉP TOÁN VECTƠ TRONG KHÔNG GIAN',date:'SGK',link:'https://www.youtube.com/watch?v=-s19sD15ayw',type:'video'},
    {name:'BÀI 1: PHƯƠNG TRÌNH MẶT PHẲNG PHẦN 1',date:'SGK',link:'https://www.youtube.com/watch?v=_nnpTm2Ju2o',type:'video'},
    {name:'BÀI 2: PHƯƠNG TRÌNH MẶT PHẲNG PHẦN 2',date:'SGK',link:'https://www.youtube.com/watch?v=s4eXhU4B5gU',type:'video'},
    {name:'BÀI 3: PHƯƠNG TRÌNH MẶT PHẲNG PHẦN 3',date:'SGK',link:'https://www.youtube.com/watch?v=Fcn3odFMHK0',type:'video'}
  ]},
  {id:'sgk_su',name:'SGK LỊCH SỬ',desc:'Sách giáo khoa · Video bài giảng',icon:'fa-scroll',color:'violet',group:'sgk',lessons:[
    {name:'Bài 1: LIÊN HỢP QUỐC',date:'SGK',link:'https://www.youtube.com/watch?v=mwwDY8qR8Mw',type:'video'},
    {name:'Bài 2: TRẬT TỰ THẾ GIỚI TRONG CHIẾN TRANH LẠNH',date:'SGK',link:'https://www.youtube.com/watch?v=7u2UtWcCeIM',type:'video'},
    {name:'Bài 3: TRẬT TỰ THẾ GIỚI SAU CHIẾN TRANH LẠNH',date:'SGK',link:'https://www.youtube.com/watch?v=-LbgOYSkbUo',type:'video'},
    {name:'BÀI 4: SỰ RA ĐỜI VÀ PHÁT TRIỂN ASEAN',date:'SGK',link:'https://www.youtube.com/watch?v=qwL-okw4NnQ',type:'video'},
    {name:'BÀI 5: CỘNG ĐỒNG ASEAN',date:'SGK',link:'https://www.youtube.com/watch?v=KiX48BEfndY',type:'video'},
    {name:'BÀI 6: CÁCH MẠNG THÁNG TÁM NĂM 1945',date:'SGK',link:'https://www.youtube.com/watch?v=zVIrrHq8sMc',type:'video'},
    {name:'BÀI 7: KHÁNG CHIẾN CHỐNG PHÁP',date:'SGK',link:'https://www.youtube.com/watch?v=Mylhkl4aEP8',type:'video'}
  ]}
];

const THAY_CHI = {
  id:'thay_chi',name:'TOÁN THẦY CHÍ 12',desc:'Toán · Thầy Nguyễn Quốc Chí · Chuyên đề 12',icon:'fa-chalkboard-teacher',color:'red',group:'thaychi',
  lessons:[
    {name:'[TIẾT 1] Tìm khoảng Đồng biến, Nghịch biến',date:'CH1',link:'https://drive.google.com/file/d/1chkipC3u4b6v34MqTdMO0ETJRtVLYx6b/view',type:'video'},
    {name:'[TIẾT 2] Các bài toán thực tế tính đơn điệu',date:'CH1',link:'https://drive.google.com/file/d/1fZ6pK6OGAO_WcKzRXz0JN7SPfWai1Di_/view',type:'video'},
    {name:'LUYỆN TẬP TRẮC NGHIỆM ĐÚNG SAI',date:'CH1',link:'https://drive.google.com/file/d/1YXBx94QxVsqm6WGsV936m8HOWMNQW9ea/view',type:'video'},
    {name:'[TIẾT 3] Biện luận tính đơn điệu (buổi 1)',date:'CH1',link:'https://drive.google.com/file/d/1gvazwf-TSaQgZ5fIH1QIet5bxBAiZ0oZ/view',type:'video'},
    {name:'Biện luận tính đơn điệu của hàm số (buổi 2)',date:'CH1',link:'https://drive.google.com/file/d/1upygs3FzPDvHmjM_9kazm4AxpnI5PuHf/view',type:'video'},
    {name:'Biện luận tính đơn điệu của hàm số (buổi 3)',date:'CH1',link:'https://drive.google.com/file/d/1-81cBuIoYfd8ZyS8qjcDn8gb4bgqY8iC/view',type:'video'},
    {name:'TỔNG ÔN TÍNH ĐƠN ĐIỆU HÀM SỐ',date:'CH1',link:'https://drive.google.com/file/d/1I29o23EQjRRAuU7RdqMfRtan2mjFGAp4/view',type:'video'},
    {name:'[TIẾT 1] Xác định cực trị (Cực đại, cực tiểu)',date:'CH1',link:'https://drive.google.com/file/d/1Bs3_-ENQbL5Nbei5Cyjkc5LXW5ZOsdZn/view',type:'video'},
    {name:'[TIẾT 2] Khảo sát hàm số Mũ, Logarit, Lượng giác',date:'CH1',link:'https://drive.google.com/file/d/13igE-5PcN8FX4IOkg1V2tMNC3HIqJKcZ/view',type:'video'},
    {name:'LUYỆN TẬP "ĐÚNG SAI - TRẢ LỜI NGẮN"',date:'CH1',link:'https://drive.google.com/file/d/1uK05aj7WllGHngSrGblP5vSsx4y_0WEb/view',type:'video'},
    {name:'LUYỆN TẬP THÊM CỰC TRỊ HÀM SỐ',date:'CH1',link:'https://drive.google.com/file/d/1QbcNX-GZHENsC5d9rKMF0oghIa6BHUSi/view',type:'video'},
    {name:'[TIẾT 3] Biện luận cực trị hàm số Bậc 3',date:'CH1',link:'https://drive.google.com/file/d/1S3ebFQonfgq-3eCLwIZgKiREV8eqId1i/view',type:'video'},
    {name:'[TIẾT 4] Biện luận cực trị hàm số bậc 2 trên bậc 1',date:'CH1',link:'https://drive.google.com/file/d/1Uk40XmM268VuX0UZloVX2JrHmsqOM23f/view',type:'video'},
    {name:'[TIẾT 1] Tìm GTLN, GTNN của hàm số trên đoạn',date:'CH1',link:'https://drive.google.com/file/d/1cfxyRKJd-5xSD9SqOkMVI53A3UI56S9R/view',type:'video'},
    {name:'[TIẾT 2] Tìm GTLN, GTNN trên khoảng, đặt ẩn phụ',date:'CH1',link:'https://drive.google.com/file/d/1biNLghnW6lvxKCzXb67Za7OMFjvOAAoU/view',type:'video'},
    {name:'LUYỆN TẬP DẠNG BÀI "ĐÚNG SAI" GTLN - GTNN',date:'CH1',link:'https://drive.google.com/file/d/1-U0SebaV_OPThT-s-AdDvJvvOquS54I-/view',type:'video'},
    {name:'[TIẾT 3] Tìm m để hàm số đạt GTLN, GTNN',date:'CH1',link:'https://drive.google.com/file/d/1OJjY_eUF-TzgQFJP5RCJnnC2bGpzwqKr/view',type:'video'},
    {name:'[TIẾT 1] Ứng dụng đạo hàm tìm GTLN, GTNN - Thực tiễn',date:'CH1',link:'https://drive.google.com/file/d/1I9iELWE8gZ5eWWr8P_SrdxlZjkfXtN1H/view',type:'video'},
    {name:'BẤM MÁY TÍNH FX580 GIẢI ĐẠO HÀM',date:'CH1',link:'https://drive.google.com/file/d/1TSqE_ERkjLgasHqvh6-keDUIdHQSj-NC/view',type:'video'},
    {name:'[TIẾT 2] Ứng dụng đạo hàm - Khối đa diện',date:'CH1',link:'https://drive.google.com/file/d/18YdIAe4TirtF5eJLv_s6hy0RLczRAKD6/view',type:'video'},
    {name:'[TIẾT 3] Ứng dụng đạo hàm - Khối tròn xoay',date:'CH1',link:'https://drive.google.com/file/d/1T-kU1hjCyXkkCmYMDIYbP5hYNQ4p6qNU/view',type:'video'},
    {name:'[TIẾT 4] Các bài toán tối ưu lợi nhuận',date:'CH1',link:'https://drive.google.com/file/d/1y3AUaJfI5vTIt6ge9FvK63BffwbEtrUI/view',type:'video'},
    {name:'[TIẾT 5] Bài toán tăng giảm giá (Hàm cầu)',date:'CH1',link:'https://drive.google.com/file/d/1QzuyGGgEyDNjbgqFaKNO8D5w_3fMivnX/view',type:'video'},
    {name:'LUYỆN TẬP TRẮC NGHIỆM BÀI TOÁN THỰC TẾ',date:'CH1',link:'https://drive.google.com/file/d/17P70AfWoYlhe44OBUePbsSJZ4yKVvXm2/view',type:'video'},
    {name:'LUYỆN TẬP THÊM ĐÚNG SAI BÀI TOÁN THỰC TẾ',date:'CH1',link:'https://drive.google.com/file/d/1Wa7e8N5u2v6w0gQMAfmiP0I9lVgFiUVV/view',type:'video'},
    {name:'[TIẾT 1] Xác định đường tiệm cận đứng, ngang',date:'CH1',link:'https://drive.google.com/file/d/1cqVnXZZ_REo4aee2hemCFZybi_Y5z1Sz/view',type:'video'},
    {name:'[TIẾT 2] Biện luận đường tiệm cận đứng, ngang',date:'CH1',link:'https://drive.google.com/file/d/1OkFFR7IZUdxocY3tJHM1wXrrkW_dFAsE/view',type:'video'},
    {name:'[TIẾT 3] Tiệm cận xiên',date:'CH1',link:'https://drive.google.com/file/d/1Jafdl28LPDrGMZSKhIe6KN_IYypuH09R/view',type:'video'},
    {name:'[TIẾT 1] KHẢO SÁT ĐỒ THỊ HÀM SỐ BẬC 3',date:'CH1',link:'https://drive.google.com/file/d/1ioD-_oQWtHrZ1Hi6dCD4tnBhsxAY6uU2/view',type:'video'},
    {name:'[TIẾT 2] KHẢO SÁT ĐỒ THỊ PHÂN THỨC BẬC NHẤT/BẬC NHẤT',date:'CH1',link:'https://drive.google.com/file/d/1znjP5IfOj5BT1A3oMwlYZ8zpS2KScFuv/view',type:'video'},
    {name:'[TIẾT 3] KHẢO SÁT ĐỒ THỊ PHÂN THỨC BẬC 2 TRÊN BẬC 1',date:'CH1',link:'https://drive.google.com/file/d/1Oc35BF-2eAKgFwPsL31tlo2pbK36ORm9/view',type:'video'},
    {name:'[TIẾT 4] BÀI TOÁN THỰC TẾ ĐỒ THỊ',date:'CH1',link:'https://drive.google.com/file/d/18fdm_4eg-hD-VKAsSXDqjZ09_Cb0inep/view',type:'video'},
    {name:'[TIẾT 5] CÁC DẠNG ĐỒ THỊ HÀM SỐ ĐẶC BIỆT',date:'CH1',link:'https://drive.google.com/file/d/1N9g2brXKwRUmhdM-sZsiIDFG_X1Uobge/view',type:'video'},
    {name:'[TIẾT 6] ĐẾM SỐ NGHIỆM & BIỆN LUẬN PT DỰA VÀO ĐỒ THỊ',date:'CH1',link:'https://drive.google.com/file/d/1V7r5bXKxzK04EYjWGjmIgLuJN8ztnb_4/view',type:'video'},
    {name:'[TIẾT 7] CÁC BÀI TOÁN TÌM M HÀM BẬC 3, PHÂN THỨC',date:'CH1',link:'https://drive.google.com/file/d/1_zVSOeL3WpCMBPmA9SYDtxZ5bKFbFCjB/view',type:'video'},
    {name:'LUYỆN TẬP "ĐÚNG SAI" ĐỒ THỊ HÀM SỐ',date:'CH1',link:'https://drive.google.com/file/d/1boNqps3CSA9S1oUKkwFK6Xbqkk-hB7kY/view',type:'video'},
    {name:'LUYỆN TẬP "ĐÚNG SAI" TƯƠNG GIAO ĐỒ THỊ',date:'CH1',link:'https://drive.google.com/file/d/1bq0UVpcthDD_Mj-Gbjm1VTCpsY-R9F83/view',type:'video'},
    {name:'LUYỆN TẬP ĐÚNG SAI HÀM SỐ BẬC 3 - PHÂN THỨC',date:'CH1',link:'https://drive.google.com/file/d/1UwhGCmIwMl-Jv5tejWV2r5XQn2Rs4Fwy/view',type:'video'},
    {name:'LUYỆN TẬP ĐÚNG SAI HÀM PHÂN THỨC BẬC HAI/BẬC NHẤT',date:'CH1',link:'https://drive.google.com/file/d/1p3gXA5EkwfrgIP4mxkModJ_zX9UX_edE/view',type:'video'},
    {name:'[TIẾT 1] Tính đơn điệu của hàm hợp (Phần 1)',date:'CH1',link:'https://drive.google.com/file/d/1HIHKSL6i3u8VrQ3IhVpCIPkC1TCBGDu3/view',type:'video'},
    {name:'Tính đơn điệu của hàm hợp (Phần 2)',date:'CH1',link:'https://drive.google.com/file/d/1TsjGSY0U6CdKBYUSiENZnpIByGGtYGZZ/view',type:'video'},
    {name:'[TIẾT 2] Biện luận đơn điệu hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/19tsjM4wJi06j9PVyztIv1LSMriRWXkoL/view',type:'video'},
    {name:'[TIẾT 3] Luyện tập thêm',date:'CH1',link:'https://drive.google.com/file/d/19Prs6ku2OivOx6SdfQzvSQPs9DQaXz9O/view',type:'video'},
    {name:'[TIẾT 1] Cực trị hàm hợp (Buổi 1)',date:'CH1',link:'https://drive.google.com/file/d/1OrNgOkMWXPMQHxio3RXF-LLphRB9SQTx/view',type:'video'},
    {name:'Cực trị hàm hợp (Buổi 2)',date:'CH1',link:'https://drive.google.com/file/d/1zV-eFwMjEl3L2cbfVZZsm1iEEvD-qQhw/view',type:'video'},
    {name:'[TIẾT 2] Luyện tập thêm',date:'CH1',link:'https://drive.google.com/file/d/15TuRXDrDlRQPmB3KiXIHyGCpZIctrxA_/view',type:'video'},
    {name:'Minmax hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/1B35vBqXzjj7zJGvGKolRwnWVdaHtTz95/view',type:'video'},
    {name:'Tiết 1: Đếm số nghiệm hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/1jPa9LzYK6PcDRWfKMQit6Eb-PlrGUw1k/view',type:'video'},
    {name:'Tiết 2: Biện luận số nghiệm hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/16lywEP0i7tJOfbvwyg4oVMCCFTzWfibG/view',type:'video'},
    {name:'Tiết 3: Phương pháp ghép trục',date:'CH1',link:'https://drive.google.com/file/d/1HYraRktwrodNjzhXf1IupIgpuBjaTsD-/view',type:'video'},
    {name:'Tiết 4: Luyện tập thêm',date:'CH1',link:'https://drive.google.com/file/d/1PUYwwDDPGJ4vvCStSQD7eXJD-gLGa2sL/view',type:'video'},
    {name:'Tiết 1: Cực trị hàm y=|f(x)|',date:'CH1',link:'https://drive.google.com/file/d/1bv0f_TQlMFzQkIZzteuh7jy3MuonY7sy/view',type:'video'},
    {name:'Tiết 2: Cực trị hàm y=f(|x|)',date:'CH1',link:'https://drive.google.com/file/d/11lCv-RzYeYBJYXzGB0ZPbQRpKheK5yEJ/view',type:'video'},
    {name:'MIN-MAX HÀM SỐ CHỨA DẤU GIÁ TRỊ TUYỆT ĐỐI',date:'CH1',link:'https://drive.google.com/file/d/1i6UxOdqwamxvHKcZlmkwk-39MUo4lABO/view',type:'video'},
    {name:'Tiết 1: Phương trình tiếp tuyến tại điểm',date:'CH1',link:'https://drive.google.com/file/d/1axnoodSz9-f0VecL1hTd3GGjW3D1E432/view',type:'video'},
    {name:'Tiết 2: Phương trình tiếp tuyến qua điểm',date:'CH1',link:'https://drive.google.com/file/d/1N8CfD4B0-qK7oxZ_JASHeXC_67i8h-oc/view',type:'video'},
    {name:'KHÁI NIỆM VÀ QUY TẮC VECTƠ TRONG KHÔNG GIAN',date:'CH2',link:'https://drive.google.com/file/d/12kQw9UktLgj2J6BvU2vmfmaOfoOiQK0G/view',type:'video'},
    {name:'PHÉP TOÁN VECTƠ TRONG HÌNH CHÓP, TỨ DIỆN',date:'CH2',link:'https://drive.google.com/file/d/1IRsmH1TLZrIFKEDSPL0FZUBWuDIBVAFT/view',type:'video'},
    {name:'PHÉP TOÁN VECTƠ TRONG HÌNH HỘP, LĂNG TRỤ',date:'CH2',link:'https://drive.google.com/file/d/1ewQ2VkU8ujyzvPSEjM65h5ZU0DssycFq/view',type:'video'},
    {name:'PHÉP TOÁN VECTƠ TRONG LĂNG TRỤ TAM GIÁC',date:'CH2',link:'https://drive.google.com/file/d/1ZeCA4pJzMK49TAbW76nCSMtcxPnqn3iG/view',type:'video'},
    {name:'BÀI VỀ NHÀ LUYỆN TẬP',date:'CH2',link:'https://drive.google.com/file/d/1bA8Sjjs-rhXdtxaRf8TT2SRF6x59xuv5/view',type:'video'},
    {name:'ĐỀ LUYỆN TẬP: CÁC PHÉP TOÁN VECTƠ TRONG KHÔNG GIAN',date:'CH2',link:'https://drive.google.com/file/d/1YKNNZHTRmKEY2Mwc0vRefboFcwAQNkJP/view',type:'video'},
    {name:'BÀI TOÁN THỰC TẾ TỔNG HỢP LỰC',date:'CH2',link:'https://drive.google.com/file/d/1wxNkzcxHmTfGI4023eX5bM1aPM9eoUfx/view',type:'video'},
    {name:'GÓC GIỮA 2 VECTƠ - TÍCH VÔ HƯỚNG 2 VECTƠ',date:'CH2',link:'https://drive.google.com/file/d/1JuvzMCdK8grCgcM8AeIkjoMYLyYPivRn/view',type:'video'},
    {name:'ĐỀ LUYỆN TẬP: GÓC GIỮA 2 VECTƠ',date:'CH2',link:'https://drive.google.com/file/d/1L8RLcj2rRvg3bOW4-b7rxxQq8T73L1Ml/view',type:'video'},
    {name:'ĐỀ LUYỆN TẬP: ĐÚNG SAI - ĐIỀN ĐÁP ÁN',date:'CH2',link:'https://drive.google.com/file/d/1y0Fub0Ai-aR7aiu-V9635Z56JxiC68na/view',type:'video'},
    {name:'[TIẾT 1] TỌA ĐỘ ĐIỂM - CÁC CÔNG THỨC VECTƠ',date:'CH2',link:'https://drive.google.com/file/d/1MSduE1pCXQSuWqRow2d9iKZoMIlUulzn/view',type:'video'},
    {name:'[TIẾT 2] TÌM ĐIỂM THỎA MÃN ĐẲNG THỨC VECTƠ',date:'CH2',link:'https://drive.google.com/file/d/1Xo5jjgGcKByJnr7If_hpvEDrVu5HMivm/view',type:'video'},
    {name:'[TIẾT 3] TÍCH CÓ HƯỚNG CỦA VECTƠ VÀ ỨNG DỤNG',date:'CH2',link:'https://drive.google.com/file/d/1CevzkmFKtd-gqBTDhCrxQT4up3YqtVzC/view',type:'video'},
    {name:'HƯỚNG DẪN BẤM MÁY TÍNH TÍCH CÓ HƯỚNG',date:'CH2',link:'https://drive.google.com/file/d/1-OBwwfcMAQ-l9E2Ix_IivZSM4ew4I-0W/view',type:'video'},
    {name:'HƯỚNG DẪN BẤM MÁY TỌA ĐỘ VECTO TRONG OXYZ',date:'CH2',link:'https://drive.google.com/file/d/1aGMU2ZataRvIsA79r9x2KHpUE8_N-hvn/view',type:'video'},
    {name:'LUYỆN TẬP THÊM (TRẮC NGHIỆM 4 ĐÁP ÁN)',date:'CH2',link:'https://drive.google.com/file/d/1QrRL6bCAZNuudO_r3NlHZY0lHZ00uvTh/view',type:'video'},
    {name:'LUYỆN TẬP THÊM (ĐÚNG SAI - ĐIỀN ĐÁP ÁN)',date:'CH2',link:'https://drive.google.com/file/d/1J-v93tWncQZXwAnUU44SJq9dKglaJQwb/view',type:'video'},
    {name:'[TIẾT 1] NGUYÊN HÀM CƠ BẢN',date:'CH4',link:'https://youtu.be/a6A-sqViYDo',type:'video'},
    {name:'[TIẾT 2] NGUYÊN HÀM HÀM HỢP',date:'CH4',link:'https://youtu.be/prCq7C6iNss',type:'video'},
    {name:'[TIẾT 3] NGUYÊN HÀM HỮU TỈ',date:'CH4',link:'https://youtu.be/ScnKHTtPOxQ',type:'video'},
    {name:'[TIẾT 4] NGUYÊN HÀM LƯỢNG GIÁC',date:'CH4',link:'https://youtu.be/U87Fs1MZKv0',type:'video'},
    {name:'HƯỚNG DẪN BẤM MÁY TÍNH NGUYÊN HÀM',date:'CH4',link:'https://youtu.be/l2K35Z1vQak',type:'video'},
    {name:'LUYỆN TẬP THÊM NGUYÊN HÀM',date:'CH4',link:'https://youtu.be/260hLoDlULI',type:'video'},
    {name:'TÍNH TÍCH PHÂN',date:'CH4',link:'https://youtu.be/3kgqyFEFzkc',type:'video'},
    {name:'HƯỚNG DẪN BẤM MÁY TÍNH TÍCH PHÂN',date:'CH4',link:'https://youtu.be/3ku8RdmRteQ',type:'video'},
    {name:'LUYỆN TẬP THÊM TÍCH PHÂN',date:'CH4',link:'https://youtu.be/ss7RbW_FYAE',type:'video'},
    {name:'[TIẾT 1] ỨNG DỤNG NGUYÊN HÀM GIẢI BÀI HÀM TỐC ĐỘ',date:'CH4',link:'https://youtu.be/eJRmXWTHCyM',type:'video'},
    {name:'[TIẾT 2] ỨNG DỤNG CƠ HỌC - BÀI TOÁN CHUYỂN ĐỘNG',date:'CH4',link:'https://youtu.be/2fm3iPZBcwU',type:'video'},
    {name:'BÀI TOÁN CHUYỂN ĐỘNG - DẠNG BÀI ĐÚNG SAI',date:'CH4',link:'https://youtu.be/FWsUttiMSAI',type:'video'},
    {name:'[TIẾT 3] ỨNG DỤNG TÍCH PHÂN TÍNH DIỆN TÍCH',date:'CH4',link:'https://youtu.be/gyS75FR-Ing',type:'video'},
    {name:'[TIẾT 4] ỨNG DỤNG TÍCH PHÂN TÍNH DIỆN TÍCH (CÓ HÌNH)',date:'CH4',link:'https://youtu.be/xcnkGuv5ZdE',type:'video'},
    {name:'[TIẾT 5] BÀI TOÁN THỰC TẾ TÍNH DIỆN TÍCH',date:'CH4',link:'https://youtu.be/SKfPRUyellA',type:'video'},
    {name:'[TIẾT 6] TÍNH THỂ TÍCH KHỐI TRÒN XOAY',date:'CH4',link:'https://m.youtube.com/watch?v=exrmuIKHZLM',type:'video'},
    {name:'[TIẾT 7] TÍNH THỂ TÍCH KHỐI TRÒN XOAY (CÓ HÌNH)',date:'CH4',link:'https://m.youtube.com/watch?v=ohivLY7y20Y',type:'video'},
    {name:'[TIẾT 8] TÍNH THỂ TÍCH KHỐI TRÒN XOAY QUANH TRỤC TUNG',date:'CH4',link:'https://m.youtube.com/watch?v=KsyL217yQgk',type:'video'},
    {name:'[TIẾT 1] XÁC ĐỊNH CÁC YẾU TỐ, TÍNH GÓC & VỊ TRÍ TƯƠNG ĐỐI',date:'CH5',link:'https://youtu.be/HjSwPiPdy8M',type:'video'},
    {name:'[TIẾT 2] LẬP PT KHI BIẾT VECTƠ PHÁP TUYẾN & ĐIỂM',date:'CH5',link:'https://youtu.be/YKqdtVDwq3c',type:'video'},
    {name:'[TIẾT 3] LẬP PT CÓ YẾU TỐ KHOẢNG CÁCH',date:'CH5',link:'https://youtu.be/1ef2CtT4qAc',type:'video'},
    {name:'[TIẾT 1] XÁC ĐỊNH YẾU TỐ, VỊ TRÍ, KC, GÓC',date:'CH5',link:'https://youtu.be/P_kRnQX1YEA',type:'video'},
    {name:'[TIẾT 2] LẬP PT KHI BIẾT VECTƠ CHỈ PHƯƠNG & ĐIỂM',date:'CH5',link:'https://youtu.be/C5c9IclXCIg',type:'video'},
    {name:'[TIẾT 3] LẬP PT CÓ YẾU TỐ GIAO ĐIỂM',date:'CH5',link:'https://youtu.be/GuLTtsFODvE',type:'video'},
    {name:'[TIẾT 1] XÁC ĐỊNH YẾU TỐ, LẬP PT MẶT CẦU',date:'CH5',link:'https://youtu.be/h3iitITyzsM',type:'video'},
    {name:'[TIẾT 2] BÀI TOÁN VỊ TRÍ TƯƠNG ĐỐI TRONG MẶT CẦU',date:'CH5',link:'https://youtu.be/QCJM0N3wWTI',type:'video'},
    {name:'[TIẾT 3] ÔN TẬP PT MẶT CẦU - ĐÚNG SAI',date:'CH5',link:'https://youtu.be/DICVaiFcwIo',type:'video'},
    {name:'[TIẾT 4] ỨNG DỤNG THỰC TẾ MẶT CẦU',date:'CH5',link:'https://youtu.be/teMUkIFSW6s',type:'video'},
    {name:'[TIẾT 1] TÌM HÌNH CHIẾU & ĐIỂM ĐỐI XỨNG',date:'CH5',link:'https://youtu.be/nunJkhY2SUg',type:'video'},
    {name:'[TIẾT 2] BÀI TOÁN MINMAX LIÊN QUAN ĐẾN HÌNH CHIẾU',date:'CH5',link:'https://youtu.be/C8x6tSgiksU',type:'video'},
    {name:'[TIẾT 3] ĐIỂM & ĐƯỜNG ĐẶC BIỆT TRONG TAM GIÁC',date:'CH5',link:'https://youtu.be/y0Im-EaMo6Q',type:'video'},
    {name:'[TIẾT 1] CÔNG THỨC TÍNH XÁC SUẤT CÓ ĐIỀU KIỆN',date:'CH6',link:'https://youtu.be/_JPLqrLhuPw',type:'video'},
    {name:'[TIẾT 2] XS KHI BIẾT TRƯỚC XS THÀNH PHẦN',date:'CH6',link:'https://youtu.be/A1Y97N3KEPY',type:'video'},
    {name:'[TIẾT 3] XS CÓ ĐIỀU KIỆN THEO CT CỔ ĐIỂN',date:'CH6',link:'https://youtu.be/G7FZdauDaZs',type:'video'},
    {name:'[TIẾT 4] XS CÓ ĐIỀU KIỆN - ĐẾM HAI LẦN',date:'CH6',link:'https://youtu.be/EeecuYkA85U',type:'video'},
    {name:'[TIẾT 5] XS CÓ ĐIỀU KIỆN - BÀI TOÁN BI HAI HỘP',date:'CH6',link:'https://youtu.be/05MwE30cfgc',type:'video'},
    {name:'TL: [TIẾT 1] Đồng biến, Nghịch biến',date:'TL1',link:'https://drive.google.com/drive/folders/16phOwE1M58dluU3EXqXOdSYQ-SbLCE6M',type:'tailieu'},
    {name:'TL: [TIẾT 2] Bài toán thực tế đơn điệu',date:'TL1',link:'https://drive.google.com/drive/folders/1d11906EgNxJ3bZ5kB_zov8n1YVW9JkQ4',type:'tailieu'},
    {name:'TL: Luyện tập trắc nghiệm đúng sai',date:'TL1',link:'https://drive.google.com/drive/folders/1xB6NezT1w8uxxXcUl27CcqYkI8HwNX5y',type:'tailieu'},
    {name:'TL: Biện luận tính đơn điệu (buổi 1)',date:'TL1',link:'https://drive.google.com/drive/folders/10j2fxBfXorudJhh647mfzp3mB8PGdqu8',type:'tailieu'},
    {name:'TL: Biện luận tính đơn điệu (buổi 2)',date:'TL1',link:'https://drive.google.com/drive/folders/1Z48qhZu8HK5WOM-CGqwxvYdMBMuAYIa3',type:'tailieu'},
    {name:'TL: Biện luận tính đơn điệu (buổi 3)',date:'TL1',link:'https://drive.google.com/drive/folders/1YNvgnVQ186GvtbafEs3hMWnqTEQYQvuc',type:'tailieu'},
    {name:'TL: Tổng ôn tính đơn điệu',date:'TL1',link:'https://drive.google.com/drive/folders/1pAxKo0EouOPS162j9gZ_Bz8t3GS2_-ls',type:'tailieu'},
    {name:'TL: Xác định cực trị',date:'TL2',link:'https://drive.google.com/drive/folders/1A6OGMMZs7NaifQcjTRFn01SyLaJQfNVv',type:'tailieu'},
    {name:'TL: Khảo sát hàm Mũ, Logarit',date:'TL2',link:'https://drive.google.com/drive/folders/19rzdR03IjlmlTkLDV1XNrze80WpDaXEi',type:'tailieu'},
    {name:'TL: Luyện tập Đúng Sai - Trả lời ngắn',date:'TL2',link:'https://drive.google.com/drive/folders/15VsuHnuirOD0qVarB53rutWQfK2MCG8d',type:'tailieu'},
    {name:'TL: Luyện tập thêm cực trị',date:'TL2',link:'https://drive.google.com/drive/folders/1WybaGeQ3Qab8FRTHRkRCI41Vkjqsl344',type:'tailieu'},
    {name:'TL: Biện luận cực trị Bậc 3',date:'TL2',link:'https://drive.google.com/drive/folders/1bdrYW4t3JhbxVVQR9gnf6rWmuqqw2Dxw',type:'tailieu'},
    {name:'TL: Biện luận cực trị bậc 2/1',date:'TL2',link:'https://drive.google.com/drive/folders/1r192F4O4UZFpuvWZoLFlJVszyTDi6iX3',type:'tailieu'},
    {name:'TL: GTLN-GTNN trên đoạn',date:'TL3',link:'https://drive.google.com/drive/folders/1YG46gJsxJy8AmgxdZI3Wlk8Mv-E5hPX0',type:'tailieu'},
    {name:'TL: GTLN-GTNN trên khoảng',date:'TL3',link:'https://drive.google.com/drive/folders/13wqR2nzDJ5hiRWBIKuHPFm4Xz97YUO3H',type:'tailieu'},
    {name:'TL: Luyện tập Đúng Sai GTLN-GTNN',date:'TL3',link:'https://drive.google.com/drive/folders/10IwaJbNdPJgV0WsYQPN8siwPbg8AIdIj',type:'tailieu'},
    {name:'TL: Tìm m để hs đạt GTLN-GTNN',date:'TL3',link:'https://drive.google.com/drive/folders/1HoQBERU2Vkc9UMk5ReESoAa_rTY3Mdtn',type:'tailieu'},
    {name:'BTVN: [TIẾT 1] Đồng biến, Nghịch biến',date:'BTVN1',link:'https://drive.google.com/drive/folders/1HlwHHkKkdXmFLNrDFRPgx7eE1b61o1s3',type:'btvn'},
    {name:'BTVN: [TIẾT 2] Bài toán thực tế đơn điệu',date:'BTVN1',link:'https://drive.google.com/drive/folders/1HUxOOeuk5FZg9FarEBA-l_YfYZyC6th0',type:'btvn'},
    {name:'BTVN: Luyện tập trắc nghiệm',date:'BTVN1',link:'https://drive.google.com/drive/folders/1qUZvZ0yFQBQATjHHmz-QtnZqcOIi3CTg',type:'btvn'},
    {name:'BTVN: Biện luận đơn điệu (buổi 1)',date:'BTVN1',link:'https://drive.google.com/drive/folders/1NLsrlXRbxZlS0lKLw0GA_o_IBBt4GZev',type:'btvn'},
    {name:'BTVN: Biện luận đơn điệu (buổi 2)',date:'BTVN1',link:'https://drive.google.com/drive/folders/1860sPY-WT2A12yVabfOSE-EtuGPXvHkj',type:'btvn'},
    {name:'BTVN: Xác định cực trị',date:'BTVN2',link:'https://drive.google.com/drive/folders/1EkOMANT-f6r2LqR-DIqw93Kq5vaR0nXj',type:'btvn'},
    {name:'BTVN: Luyện tập Đúng Sai - Trả lời ngắn',date:'BTVN2',link:'https://drive.google.com/drive/folders/1IlKWvpK1A_bQYP7vHTCP4-Z1iCtQys2D',type:'btvn'},
    {name:'BTVN: Luyện tập thêm cực trị',date:'BTVN2',link:'https://drive.google.com/drive/folders/1zxqAP2wZKRttZYFKMkZHcYIfTH8IOYoR',type:'btvn'},
    {name:'BTVN: GTLN-GTNN trên đoạn',date:'BTVN3',link:'https://drive.google.com/drive/folders/1GtjZE100qb87gZvYuOc4s-GGj6dD6YES',type:'btvn'},
    {name:'BTVN: GTLN-GTNN trên khoảng',date:'BTVN3',link:'https://drive.google.com/drive/folders/1Nkbab9E_hESVecGJw72eTMevxVM-Blpn',type:'btvn'},
    {name:'BTVN: Tìm m để đạt GTLN-GTNN',date:'BTVN3',link:'https://drive.google.com/drive/folders/1PflWFfAw1aGEYGIYmylZ-lDrBKCe2CUL',type:'btvn'},
    {name:'BTVN: Ứng dụng thực tiễn',date:'BTVN4',link:'https://drive.google.com/drive/folders/1TgnxtxuqEWAVO-qvjfzpKxMIzpkTlX73',type:'btvn'},
    {name:'BTVN: Luyện tập trắc nghiệm thực tế',date:'BTVN4',link:'https://drive.google.com/drive/folders/1GQNP0JxTphcJs-qBNyQ4BkLygwOuMZBC',type:'btvn'},
    {name:'BTVN: Tiệm cận đứng, ngang',date:'BTVN5',link:'https://drive.google.com/drive/folders/1O9iq8GqchiQStGrEDtE8g9Pla2dIZzdz',type:'btvn'},
    {name:'BTVN: Biện luận tiệm cận',date:'BTVN5',link:'https://drive.google.com/drive/folders/13VRWQcK9iVGsyKZ-8rAYuBWMsS3A4ABC',type:'btvn'},
    {name:'BTVN: Tiệm cận xiên',date:'BTVN5',link:'https://drive.google.com/drive/folders/1IVBOOYU4RdZcY0PtZMW41zRQKpiluOcO',type:'btvn'},
    {name:'Chữa BTVN: [TIẾT 1] Đơn điệu',date:'CB1',link:'https://drive.google.com/file/d/1kkHZlQXccIseM7kTUvR4oYGiYPXvE1UQ/view',type:'btvn'},
    {name:'Chữa BTVN: [TIẾT 2] Thực tế đơn điệu',date:'CB1',link:'https://drive.google.com/file/d/1AFCJ2W6WNbm_ZBwA2tj47SKdcFFi4fGo/view',type:'btvn'},
    {name:'Chữa BTVN: Luyện tập trắc nghiệm',date:'CB1',link:'https://drive.google.com/file/d/1WPGSVYACF9OlXzfFA_ClkyMFIGJs3wAF/view',type:'btvn'},
    {name:'Chữa BTVN: Biện luận (buổi 1)',date:'CB1',link:'https://drive.google.com/file/d/1UnRcBisPMfwll0wkMt6AWI9Ri1XPF3sf/view',type:'btvn'},
    {name:'Chữa BTVN: Biện luận (buổi 2)',date:'CB1',link:'https://drive.google.com/file/d/1SSir6emREc9Zmkhfa0WgB4E8ZS_pASO_/view',type:'btvn'},
    {name:'Chữa BTVN: Biện luận (buổi 3)',date:'CB1',link:'https://drive.google.com/file/d/17DQIv8CuUH4U5ZZvDjCe8CKgZ7-yQsI5/view',type:'btvn'},
    {name:'Chữa BTVN: Xác định cực trị',date:'CB2',link:'https://drive.google.com/file/d/1yZc1hbiuVcQzFpt3AMbtRWNEPVYMUsUz/view',type:'btvn'},
    {name:'Chữa BTVN: Luyện tập Đúng Sai',date:'CB2',link:'https://drive.google.com/file/d/1U06vDWN9XVuxDgAqQWcld64F2hTp0HDP/view',type:'btvn'},
    {name:'Chữa BTVN: Luyện tập thêm cực trị',date:'CB2',link:'https://drive.google.com/file/d/1faNGVvHpvIXOeDY4G66nVdChjK5ohDaN/view',type:'btvn'},
    {name:'Chữa BTVN: GTLN-GTNN trên đoạn',date:'CB3',link:'https://drive.google.com/file/d/1HAOxa3KSPE5C9RiUD7Pkk5m1bcirFgg-/view',type:'btvn'},
    {name:'Chữa BTVN: GTLN-GTNN trên khoảng',date:'CB3',link:'https://drive.google.com/file/d/1eWJVKNjTmwLGTQ_R0aK1keuiald7IOyG/view',type:'btvn'},
    {name:'Chữa BTVN: Tìm m để đạt GTLN-GTNN',date:'CB3',link:'https://drive.google.com/file/d/1asQK5gROZ_YoGrqIHBOxp1H09e2bpjTH/view',type:'btvn'},
    {name:'Chữa BTVN: Ứng dụng thực tiễn',date:'CB4',link:'https://drive.google.com/file/d/1N9Uwd7ORE8-BlsPcoPQCdmupEq3dONqW/view',type:'btvn'},
    {name:'Chữa BTVN: Luyện tập thực tế',date:'CB4',link:'https://drive.google.com/file/d/1dr3dT4eD8h1gno_JycPG6keepz1f8Qje/view',type:'btvn'},
    {name:'Chữa BTVN: Tiệm cận đứng, ngang',date:'CB5',link:'https://drive.google.com/file/d/1y1boQtotrrk0zPNpubJxCKVpxNV2dQ6v/view',type:'btvn'},
    {name:'Chữa BTVN: Biện luận tiệm cận',date:'CB5',link:'https://drive.google.com/file/d/1UCTVmC3IsnigPy77UdfXgwQdVnxWAu_a/view',type:'btvn'},
    {name:'Chữa BTVN: Tiệm cận xiên',date:'CB5',link:'https://drive.google.com/file/d/1HFCJg4_drWucY0DKUQDhqcrMsysMRThg/view',type:'btvn'}
  ]
};

const CO_SEN = {
  id:'co_sen',name:'SỬ CÔ HƯƠNG SEN',desc:'Lịch sử · Cô Hương Sen · Lớp 12',icon:'fa-scroll',color:'pink',group:'cosen',
  lessons:[
    {name:'Bài 1 Liên hợp quốc',date:'Bài 1',link:'https://youtu.be/-LoBn5WekkM',type:'video'},
    {name:'Đề số 1',date:'Đề 1',link:'https://youtu.be/iTv2dbhB6kc',type:'video'},
    {name:'Bài 2',date:'Bài 2',link:'https://www.youtube.com/playlist?list=PL3ZewEXRtOFRUMxG3J0r_trFcARyRhHtq',type:'video'},
    {name:'Đề số 2',date:'Đề 2',link:'https://youtu.be/mX9_NYv4l1s',type:'video'},
    {name:'Bài 3 Trật tự thế giới sau chiến tranh',date:'Bài 3',link:'https://youtu.be/BB74hjcOXHY',type:'video'},
    {name:'Đề số 3',date:'Đề 3',link:'https://youtu.be/2t85Pwx6c8o',type:'video'},
    {name:'Bài 4 Sự ra đời ASEAN P1',date:'Bài 4',link:'https://youtu.be/XTVAnMGdZgs',type:'video'},
    {name:'Bài 4 Sự ra đời ASEAN P2',date:'Bài 4',link:'https://youtu.be/ccDyaWyTK4g',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 4 P1',date:'Bài 4',link:'https://youtu.be/8fGV7gzRguY',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 4 P2',date:'Bài 4',link:'https://youtu.be/RQ45gCmE8_E',type:'video'},
    {name:'Bài 5 Cộng đồng ASEAN',date:'Bài 5',link:'https://youtu.be/vufhxU2oWb0',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 5',date:'Bài 5',link:'https://youtu.be/SRpwasmQQPI',type:'video'},
    {name:'Bài 6 CMT8 - 1945 P1',date:'Bài 6',link:'https://youtu.be/sNc4GKb8UPQ',type:'video'},
    {name:'Bài 6 CMT8 - 1945 P2',date:'Bài 6',link:'https://youtu.be/3h_-nbnNrrQ',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 6',date:'Bài 6',link:'https://youtu.be/Kiuc8mCKGiw',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P1',date:'Bài 7',link:'https://youtu.be/TFhooXZJTro',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P2',date:'Bài 7',link:'https://youtu.be/xqS76zxWhHA',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P3',date:'Bài 7',link:'https://youtu.be/4hWfSgPxC2Q',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P4',date:'Bài 7',link:'https://youtu.be/Qkx_0zLGj9M',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P5',date:'Bài 7',link:'https://youtu.be/q-I-XBgKrzI',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 7',date:'Bài 7',link:'https://youtu.be/au3fXOvE-zg',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P1',date:'Bài 8',link:'https://youtu.be/38MhsbYfRUc',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P2',date:'Bài 8',link:'https://youtu.be/asEsharpkbk',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P3',date:'Bài 8',link:'https://youtu.be/9K60masA3iQ',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P4',date:'Bài 8',link:'https://youtu.be/SO-2ErNYcVA',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 8',date:'Bài 8',link:'https://youtu.be/WjAmG5_7VX0',type:'video'},
    {name:'Bài 9: 1975 - Nay',date:'Bài 9',link:'https://youtu.be/G46xH-XQcgY',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 9',date:'Bài 9',link:'https://youtu.be/QaKhCQub_VU',type:'video'},
    {name:'Bài 10: Việt Nam từ 1986 đến nay',date:'Bài 10',link:'https://www.youtube.com/playlist?list=PL3ZewEXRtOFTzOO5uJxdMd-7_0iybgNdS',type:'video'},
    {name:'CHỮA ĐỀ LUYỆN BÀI 10',date:'Bài 10',link:'https://youtu.be/-ebwiIPHRfU',type:'video'}
  ]
};
