/* ============================================================
   WeX EDUCATION — DATA
   Tách từ Local_Tieng_Anh.html + tất cả khóa học
   ============================================================ */

const MEGA_SUBJECTS = [
  {id:'toan_co_ban',name:'TOÁN CƠ BẢN',desc:'Toán · HSA · Chuyên đề 12',icon:'📐',color:'green',group:'hsa',lessons:[
    {name:'Khoảng cách từ điểm đến mp-Góc trong KG',date:'10/04',link:'https://www.youtube.com/watch?v=jEJu4H_cUSs',type:'video'},
    {name:'Khoảng cách từ điểm đến MP ( tiếp)',date:'17/04',link:'https://www.youtube.com/watch?v=t3Vw_yxlgHI',type:'video'},
    {name:'Khoảng cách giữa 2 ĐT chéo nhau',date:'24/04',link:'https://www.youtube.com/watch?v=LQQrSZvD5Os',type:'video'},
    {name:'Công thức DKH tính KC giữa 2 ĐT',date:'05/05',link:'https://www.youtube.com/watch?v=tgPdx8EEfsk',type:'video'},
    {name:'Công thức DKH tính KC giữa 2 ĐT-TIẾP',date:'08/05',link:'https://www.youtube.com/watch?v=FZ1xjaVf38s',type:'video'},
    {name:'Thể tích',date:'12/05',link:'https://www.youtube.com/watch?v=c9cIE6m6r3c',type:'video'},
    {name:'Tính đơn điệu của hàm số',date:'15/05',link:'https://www.youtube.com/watch?v=kagwiaGQ00I',type:'video'},
    {name:'Cực trị của hàm số',date:'19/05',link:'https://www.youtube.com/watch?v=Hv38t3-E6ME',type:'video'},
    {name:'GTLN-GTNN của hàm số',date:'22/05',link:'https://www.youtube.com/watch?v=hsAErSmUpUc',type:'video'},
    {name:'Đường tiệm cận của Đồ thị hàm số',date:'26/05',link:'https://www.youtube.com/watch?v=SZPl80hyXCo',type:'video'},
    {name:'Khảo sát sự Biến thiên và vẽ ĐTHS',date:'29/05',link:'https://www.youtube.com/watch?v=8a9rXTS750M',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ T5 - ĐỊNH LƯỢNG',date:'01/06',link:'https://www.youtube.com/watch?v=zL5faREUzLQ',type:'video'},
    {name:'Khảo sát hàm phân thức',date:'03/06',link:'https://www.youtube.com/watch?v=WrugSPSW6t4',type:'video'},
    {name:'Khảo sát hàm phân thức-Tiếp',date:'06/06',link:'https://www.youtube.com/watch?v=nk7Gse2CK40',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://www.youtube.com/watch?v=rhlaiNxmki0',type:'video'},
    {name:'Cực trị của Hàm hợp',date:'12/06',link:'https://www.youtube.com/watch?v=mYKfj3T6tm0',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp-Tiếp',date:'16/06',link:'https://www.youtube.com/watch?v=yaRCocsWjXw',type:'video'},
    {name:'GTLN-GTNN của Hàm hợp',date:'19/06',link:'https://www.youtube.com/watch?v=OAgwmfNl6mI',type:'video'},
    {name:'Tương giao của Đồ thị HS',date:'23/06',link:'https://www.youtube.com/watch?v=XiXOX9xnWzE',type:'video'},
    {name:'Tương giao của Đồ thị HS - Tiếp',date:'27/06',link:'https://www.youtube.com/watch?v=9xQu8B1bAJA',type:'video'},
    {name:'(Có tham số) Tính đơn điệu của Hàm số',date:'30/06',link:'https://www.youtube.com/watch?v=9JJQGipRT54',type:'video'},
    {name:'(Có tham số) Tính đơn điệu - Tiếp',date:'03/07',link:'https://www.youtube.com/watch?v=pYglUBnSSJU',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P1)',date:'07/07',link:'https://www.youtube.com/watch?v=qcfXhfvBTyU',type:'video'},
    {name:'(Có tham số) Cực trị (P1) - Tiếp',date:'10/07',link:'https://www.youtube.com/watch?v=3GW8z4P6wvQ',type:'video'},
    {name:'(Có tham số) Cực trị của Hàm số (P2)',date:'14/07',link:'https://www.youtube.com/watch?v=R4BmwVUUiZg',type:'video'},
    {name:'Biện luận số nghiệm của PT',date:'17/07',link:'https://www.youtube.com/watch?v=tglFDtvHiG0',type:'video'},
    {name:'Biện luận số nghiệm của PT - Tiếp',date:'21/07',link:'https://www.youtube.com/watch?v=JW0GrPcDrGE',type:'video'},
    {name:'Đường tiệm cận chứa tham số m',date:'24/07',link:'https://www.youtube.com/watch?v=Fk_4Kk-39bA',type:'video'},
    {name:'Vectơ và các phép toán vectơ trong KG',date:'28/07',link:'https://www.youtube.com/watch?v=y3MqAmS6icI',type:'video'},
    {name:'Vectơ và các phép toán vectơ KG - Tiếp',date:'31/07',link:'https://www.youtube.com/watch?v=J1igzZW_i_s',type:'video'},
    {name:'Hệ trục toạ độ trong không gian',date:'04/08',link:'https://www.youtube.com/watch?v=gHYXMiebGY8',type:'video'},
    {name:'Hệ trục toạ độ trong không gian - Tiếp',date:'06/08',link:'https://www.youtube.com/watch?v=cMJ77JGb44Y',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ THÁNG 7',date:'10/08',link:'https://www.youtube.com/watch?v=ZzIjOyG8Dv8',type:'video'},
    {name:'Biểu thức toạ độ các phép toán vectơ',date:'11/08',link:'https://www.youtube.com/watch?v=i1s2L1v9MUw',type:'video'},
    {name:'Biểu thức toạ độ vectơ - Tiếp',date:'14/08',link:'https://www.youtube.com/watch?v=hHdeZUGo5hc',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://www.youtube.com/watch?v=WuQVuuUC-Mc',type:'video'},
    {name:'B17. Tâm tỉ cự - Tiếp',date:'21/08',link:'https://www.youtube.com/watch?v=PJokQjhQlpM',type:'video'},
    {name:'B17. Tâm tỉ cự - Tiếp',date:'25/08',link:'https://www.youtube.com/watch?v=m5A9BMaSni4',type:'video'},
    {name:'B19. Mẫu số liệu + Phương sai',date:'28/08',link:'https://www.youtube.com/watch?v=-umtsPNjfos',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ ĐỊNH LƯỢNG THÁNG',date:'04/09',link:'https://www.youtube.com/watch?v=n9pc8PtU7SU',type:'video'},
    {name:'B20. Nguyên hàm và tính chất',date:'08/09',link:'https://www.youtube.com/watch?v=oIKRJeF95KQ',type:'video'},
    {name:'B20. Nguyên hàm - Tiếp',date:'11/09',link:'https://www.youtube.com/watch?v=zpvTcO6idms',type:'video'},
    {name:'TL: Khoảng cách từ điểm đến mp',date:'10/04',link:'https://drive.google.com/uc?export=download&id=1EnwCYK-TqJRkaQIsvye5pBHS-IPw8lzs',type:'tailieu'},
    {name:'TL: Khoảng cách giữa 2 ĐT chéo nhau',date:'24/04',link:'https://drive.google.com/uc?export=download&id=1MtQfAsKQUn0mmNvoata1vMqzj4rGZrK6',type:'tailieu'},
    {name:'TL: Thể tích',date:'12/05',link:'https://drive.google.com/uc?export=download&id=1XnC0qR5qStNQZi0oToLEzrhEeuHSSaEC',type:'tailieu'},
    {name:'TL: Tính đơn điệu của hàm số',date:'15/05',link:'https://drive.google.com/uc?export=download&id=1MUqJmD_jQ1xborohVlnYt-bkoRnAyX1l',type:'tailieu'},
    {name:'TL: Cực trị của hàm số',date:'19/05',link:'https://drive.google.com/uc?export=download&id=1lCQDr4ObqjT_pc9Uqndv7TtN-MAo_1qW',type:'tailieu'},
    {name:'BTVN: Khoảng cách từ điểm đến mp',date:'10/04',link:'https://drive.google.com/drive/folders/1GtjZE100qb87gZvYuOc4s-GGj6dD6YES',type:'btvn'},
    {name:'Chữa BTVN: Tính đơn điệu',date:'19/05',link:'https://drive.google.com/file/d/1HAOxa3KSPE5C9RiUD7Pkk5m1bcirFgg-/view',type:'btvn'}
  ]},
  {id:'toan_nang_cao',name:'TOÁN NÂNG CAO',desc:'Toán · HSA · Nâng cao',icon:'📈',color:'violet',group:'hsa',lessons:[
    {name:'Khoảng cách giữa 2 ĐT chéo nhau',date:'14/04',link:'https://www.youtube.com/watch?v=lkIdIf1aKSP4',type:'video'},
    {name:'Công thức DKH tính khoảng cách 2 ĐT',date:'21/04',link:'https://www.youtube.com/watch?v=jBNvSSnaDSg',type:'video'},
    {name:'Thể tích',date:'28/04',link:'https://www.youtube.com/watch?v=q5YufpNSBSw',type:'video'},
    {name:'Bài toán nước dâng',date:'07/05',link:'https://www.youtube.com/watch?v=s26weHYHNPA',type:'video'},
    {name:'Tính đơn điệu của hàm số',date:'12/05',link:'https://www.youtube.com/watch?v=5hRO3HyzU5A',type:'video'},
    {name:'Cực trị của hàm số',date:'14/05',link:'https://www.youtube.com/watch?v=99z_rvIgmko',type:'video'},
    {name:'GTLN-GTNN của hàm số',date:'21/05',link:'https://www.youtube.com/watch?v=ExCVQXMNYGs',type:'video'},
    {name:'Đường tiệm cận của ĐTHS',date:'26/05',link:'https://www.youtube.com/watch?v=oo1PlNrIork',type:'video'},
    {name:'Khảo sát và vẽ ĐTHS',date:'28/05',link:'https://www.youtube.com/watch?v=ZjNS83DGemA',type:'video'},
    {name:'Khảo sát hàm phân thức',date:'03/06',link:'https://www.youtube.com/watch?v=18OR9kzkG8M',type:'video'},
    {name:'Tính đơn điệu của Hàm hợp',date:'09/06',link:'https://www.youtube.com/watch?v=QBXPNii6PrI',type:'video'},
    {name:'Cực trị của hàm hợp',date:'11/06',link:'https://www.youtube.com/watch?v=VCYj7u5d8PI',type:'video'},
    {name:'GTLN-GTNN của Hàm hợp',date:'16/06',link:'https://www.youtube.com/watch?v=qeOeqnfIVfA',type:'video'},
    {name:'(Có tham số) Tính đơn điệu',date:'30/06',link:'https://www.youtube.com/watch?v=KfYkNet0dig',type:'video'},
    {name:'Hàm số có chứa dấu GTTĐ',date:'04/07',link:'https://www.youtube.com/watch?v=uOAE8uqt0u4',type:'video'},
    {name:'(Có tham số) Cực trị (P1)',date:'07/07',link:'https://www.youtube.com/watch?v=Uv3bHBj-lHw',type:'video'},
    {name:'(Có tham số) Cực trị (P2)',date:'14/07',link:'https://www.youtube.com/watch?v=FCQvHw4gHgM',type:'video'},
    {name:'Biện luận số nghiệm của PT',date:'16/07',link:'https://www.youtube.com/watch?v=48P04cgewAU',type:'video'},
    {name:'Vectơ trong không gian',date:'28/07',link:'https://www.youtube.com/watch?v=b31ncDC1hwE',type:'video'},
    {name:'Hệ trục toạ độ trong không gian',date:'04/08',link:'https://www.youtube.com/watch?v=dtHvaqyI_Ao',type:'video'},
    {name:'Biểu thức toạ độ các phép toán vectơ',date:'13/08',link:'https://www.youtube.com/watch?v=7fGquJpArys',type:'video'},
    {name:'B17. Tâm tỉ cự và tích có hướng',date:'18/08',link:'https://www.youtube.com/watch?v=pUuIB4lb-yw',type:'video'},
    {name:'B20. Nguyên hàm và tính chất',date:'03/09',link:'https://www.youtube.com/watch?v=SwdIimp4kOE',type:'video'},
    {name:'B21. Tích phân và tính chất',date:'10/09',link:'https://www.youtube.com/watch?v=aQva_PEDX0A',type:'video'}
  ]},
  {id:'toan_mat_goc',name:'TOÁN MẤT GỐC',desc:'Toán · Bổ trợ mất gốc',icon:'🧩',color:'amber',group:'hsa',lessons:[
    {name:'Đơn điệu',date:'06/08',link:'https://www.youtube.com/watch?v=2fdELuVqzEU',type:'video'},
    {name:'Song trục hàm ẩn',date:'19/08',link:'https://www.youtube.com/watch?v=iPsWb1IsG8M',type:'video'},
    {name:'Đơn điệu hàm số chứa tham số',date:'26/08',link:'https://www.youtube.com/watch?v=v7puLuDFLHI',type:'video'},
    {name:'TL: Đơn điệu',date:'06/08',link:'https://drive.google.com/uc?export=download&id=1n8UBjMJ4GuFcqx_iGbQOIbod7cy_sRIH',type:'tailieu'},
    {name:'TL: Song trục hàm ẩn',date:'19/08',link:'https://drive.google.com/uc?export=download&id=180ebAPFOfFAMk5QqSnJntT7S7yZIbKF3',type:'tailieu'}
  ]},
  {id:'van_co_ban',name:'VĂN CƠ BẢN',desc:'Ngữ văn · HSA · Lớp 12',icon:'📖',color:'violet',group:'hsa',lessons:[
    {name:'Tổng quan chương trình',date:'12/04',link:'https://www.youtube.com/watch?v=Z-w9VSavfms',type:'video'},
    {name:'Khái quát về từ Tiếng Việt',date:'19/04',link:'https://www.youtube.com/watch?v=hB-g9ln_050',type:'video'},
    {name:'Biện pháp tu từ về từ',date:'07/05',link:'https://www.youtube.com/watch?v=blxHvOEP4Ig',type:'video'},
    {name:'Khái quát tiến trình VHVN',date:'16/05',link:'https://www.youtube.com/watch?v=Y9DWFwIy8Ps',type:'video'},
    {name:'Phong cách ngôn ngữ',date:'17/05',link:'https://www.youtube.com/watch?v=eC9tqrBlvkU',type:'video'},
    {name:'Đặc điểm Văn học VN',date:'30/05',link:'https://www.youtube.com/watch?v=Sr6-0HxQVFs',type:'video'},
    {name:'Văn bản nghị luận',date:'04/06',link:'https://www.youtube.com/watch?v=EGcJkMDuCM0',type:'video'},
    {name:'6 Thao tác lập luận',date:'14/06',link:'https://www.youtube.com/watch?v=zzTFiVZEQ5k',type:'video'},
    {name:'Chuyên đề đọc hiểu',date:'21/06',link:'https://www.youtube.com/watch?v=7iDv0pAjupQ',type:'video'},
    {name:'Đặc điểm Văn học trung đại',date:'26/06',link:'https://www.youtube.com/watch?v=xix1WsQzwAc',type:'video'},
    {name:'Đọc hiểu thơ mới',date:'19/07',link:'https://www.youtube.com/watch?v=ulkMdoUd1V8',type:'video'},
    {name:'Đọc hiểu truyện',date:'26/07',link:'https://www.youtube.com/watch?v=6obgoFQN5Jk',type:'video'},
    {name:'CHỮA ĐỀ THI THỬ THÁNG 7',date:'17/08',link:'https://www.youtube.com/watch?v=IpIFcC1ibjo',type:'video'},
    {name:'Thể loại kí',date:'13/09',link:'https://www.youtube.com/watch?v=7Z6PeZvTKZo',type:'video'}
  ]},
  {id:'tieng_anh',name:'TIẾNG ANH',desc:'Tiếng Anh · HSA · Lớp 12',icon:'🌐',color:'amber',group:'hsa',lessons:[
    {name:'Thì ĐT (Đơn, Tiếp Diễn)',date:'09/04',link:'https://www.youtube.com/watch?v=ctgcJ5Ig4w8',type:'video'},
    {name:'Vocab: Sports, Healthy',date:'15/04',link:'https://www.youtube.com/watch?v=UX8jskaVvoE',type:'video'},
    {name:'Thì ĐT (Tiếp Diễn, Hoàn thành)',date:'13/05',link:'https://www.youtube.com/watch?v=fQ7HdUGHdYw',type:'video'},
    {name:'Vocab: Travel & Tourism',date:'17/05',link:'https://www.youtube.com/watch?v=GixszVOzSJ4',type:'video'},
    {name:'Thì Hoàn thành tiếp diễn',date:'03/06',link:'https://www.youtube.com/watch?v=2UU5p0hmBZQ',type:'video'},
    {name:'Vocab: Environment',date:'07/06',link:'https://www.youtube.com/watch?v=sYJ1LHZTvqU',type:'video'},
    {name:'Sự phối hợp thì',date:'10/06',link:'https://www.youtube.com/watch?v=6PS8aWYxmzs',type:'video'},
    {name:'Vocab: Education',date:'28/06',link:'https://www.youtube.com/watch?v=bM_cj3TzVtE',type:'video'},
    {name:'Sự hoà hợp Chủ ngữ - Động từ',date:'01/07',link:'https://www.youtube.com/watch?v=3aWdlDYf-Qg',type:'video'},
    {name:'Vocab: Science and technology',date:'19/07',link:'https://www.youtube.com/watch?v=PDAnkyY4K18',type:'video'},
    {name:'Modal verbs',date:'22/07',link:'https://www.youtube.com/watch?v=gZuUDItZWP4',type:'video'},
    {name:'Word formation',date:'02/08',link:'https://www.youtube.com/watch?v=_bgR_VlKFnQ',type:'video'},
    {name:'Câu bị động',date:'05/08',link:'https://www.youtube.com/watch?v=BnwCJvc8hlA',type:'video'},
    {name:'Vocab: Work and Employment',date:'23/08',link:'https://www.youtube.com/watch?v=_B9rcQOqkWk',type:'video'},
    {name:'Reported speech',date:'26/08',link:'https://www.youtube.com/watch?v=3_vTGZy6vt4',type:'video'}
  ]},
  {id:'vat_ly',name:'VẬT LÝ',desc:'Vật lý · HSA · Lớp 12',icon:'⚛️',color:'green',group:'hsa',lessons:[
    {name:'Động học chất điểm',date:'02/07',link:'https://www.youtube.com/watch?v=ibliEnzO2WM',type:'video'},
    {name:'Động học chất điểm - Tiếp',date:'13/07',link:'https://www.youtube.com/watch?v=TZCOVCtXPTg',type:'video'},
    {name:'Rơi tự do',date:'06/08',link:'https://www.youtube.com/watch?v=TeDiQvXadzg',type:'video'},
    {name:'Rơi tự do - Tiếp',date:'12/08',link:'https://www.youtube.com/watch?v=RDjefjKbkCE',type:'video'},
    {name:'Động lực học chất điểm',date:'13/08',link:'https://www.youtube.com/watch?v=7WGeVkzR3Z0',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'20/08',link:'https://www.youtube.com/watch?v=_ibgvhvJ5S8',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'03/09',link:'https://www.youtube.com/watch?v=YTMA49sZgzM',type:'video'},
    {name:'Động lực học chất điểm - Tiếp',date:'10/09',link:'https://www.youtube.com/watch?v=eK67If5X1AE',type:'video'}
  ]},
  {id:'hoa_hoc',name:'HOÁ HỌC',desc:'Hoá học · HSA · Lớp 12',icon:'⚗️',color:'amber',group:'hsa',lessons:[
    {name:'Ester lipid',date:'04/07',link:'https://www.youtube.com/watch?v=m3x1-W1V2Hc',type:'video'},
    {name:'Xà phòng',date:'16/07',link:'https://www.youtube.com/watch?v=SPaQ4U_wEA8',type:'video'},
    {name:'Luyện Tập ester lipid',date:'18/07',link:'https://www.youtube.com/watch?v=ZqcJ1GG_hZM',type:'video'},
    {name:'Carbohydrate',date:'25/07',link:'https://www.youtube.com/watch?v=BI2brc000g4',type:'video'},
    {name:'Amine',date:'07/08',link:'https://www.youtube.com/watch?v=Wtxl70xV-bY',type:'video'},
    {name:'Amino acid',date:'11/08',link:'https://www.youtube.com/watch?v=ZD5SO9CMWU8',type:'video'},
    {name:'Peptide Protein',date:'15/08',link:'https://www.youtube.com/watch?v=d6AYWcWDwl0',type:'video'},
    {name:'Đại cương Polymer',date:'21/08',link:'https://www.youtube.com/watch?v=kQFU4jyMELw',type:'video'},
    {name:'Thế điện cực',date:'08/09',link:'https://www.youtube.com/watch?v=Wi7SToBoZk4',type:'video'},
    {name:'Điện phân',date:'11/09',link:'https://www.youtube.com/watch?v=kC7IX2XB5ms',type:'video'}
  ]},
  {id:'sinh_hoc',name:'SINH HỌC',desc:'Sinh học · HSA · Lớp 12',icon:'🧬',color:'green',group:'hsa',lessons:[
    {name:'Ôn tập di truyền phân tử (P1)',date:'29/06',link:'https://www.youtube.com/watch?v=NE0uuL60kdA',type:'video'},
    {name:'Ôn tập di truyền phân tử (P2)',date:'13/07',link:'https://www.youtube.com/watch?v=FA5fEpxUoxU',type:'video'},
    {name:'Ôn tập di truyền phân tử (P3)',date:'27/07',link:'https://www.youtube.com/watch?v=QdY4WPDWDaQ',type:'video'},
    {name:'Tổng ôn di truyền NST',date:'10/08',link:'https://www.youtube.com/watch?v=vjO-GnXttls',type:'video'},
    {name:'Tổng ôn quy luật di truyền (P1)',date:'24/08',link:'https://www.youtube.com/watch?v=2Nc-8IIx9HA',type:'video'},
    {name:'Tổng ôn quy luật di truyền (P2)',date:'14/09',link:'https://www.youtube.com/watch?v=mr-gY4X5FEA',type:'video'}
  ]},
  {id:'lich_su',name:'LỊCH SỬ (HSA)',desc:'Lịch sử · HSA · Lớp 12',icon:'🏛️',color:'violet',group:'hsa',lessons:[
    {name:'Liên Hợp Quốc',date:'03/07',link:'https://www.youtube.com/watch?v=OWs24pIJsYI',type:'video'},
    {name:'Trật tự thế giới trong Chiến tranh lạnh',date:'10/07',link:'https://www.youtube.com/watch?v=n_MQrIOIYDM',type:'video'},
    {name:'Trật tự thế giới sau Chiến tranh lạnh',date:'17/07',link:'https://www.youtube.com/watch?v=6vp3TMaV-r0',type:'video'},
    {name:'Sự ra đời của Asean',date:'08/08',link:'https://www.youtube.com/watch?v=G8l13tpwgMg',type:'video'},
    {name:'Cộng đồng Asean',date:'14/08',link:'https://www.youtube.com/watch?v=y6V8NrhhNuo',type:'video'},
    {name:'Cách mạng tháng 8',date:'26/08',link:'https://www.youtube.com/watch?v=dQB3swcF90I',type:'video'},
    {name:'Kháng chiến chống Pháp',date:'12/09',link:'https://www.youtube.com/watch?v=9-qQqTM8AGE',type:'video'}
  ]},
  {id:'dia_ly',name:'ĐỊA LÝ',desc:'Địa lý · HSA · Lớp 12',icon:'🌏',color:'green',group:'hsa',lessons:[
    {name:'Vị trí địa lí và khí hậu',date:'30/06',link:'https://www.youtube.com/watch?v=-M2ZMjgmqHA',type:'video'},
    {name:'Đặc điểm thiên nhiên VN',date:'14/07',link:'https://www.youtube.com/watch?v=t9y4Agvul90',type:'video'},
    {name:'Sự phân hoá đa dạng thiên nhiên',date:'21/07',link:'https://www.youtube.com/watch?v=985mMNNzHog',type:'video'},
    {name:'Dân số và lao động',date:'18/08',link:'https://www.youtube.com/watch?v=e-pp-h82NOQ',type:'video'},
    {name:'Công thức tính toán Địa lý Dân cư',date:'08/09',link:'https://www.youtube.com/watch?v=dP-Bg3E4ScU',type:'video'}
  ]}
];

const SGK_SUBJECTS = [
  {id:'sgk_toan',name:'SGK TOÁN',desc:'Sách giáo khoa · Video bài giảng',icon:'📐',color:'green',group:'sgk',lessons:[
    {name:'Bài 1: TÍNH ĐƠN ĐIỆU',date:'SGK',link:'https://www.youtube.com/watch?v=vqkvTdGX5c8',type:'video'},
    {name:'Bài 2: TÍNH ĐƠN ĐIỆU - P2',date:'SGK',link:'https://www.youtube.com/watch?v=G5NXZbxmM-A',type:'video'},
    {name:'Bài 3: CỰC TRỊ CỦA HÀM SỐ',date:'SGK',link:'https://www.youtube.com/watch?v=Z_9UpGK991M',type:'video'},
    {name:'Bài 4: CỰC TRỊ HÀM SỐ - P2',date:'SGK',link:'https://www.youtube.com/watch?v=40WVbV3G540',type:'video'},
    {name:'Bài 5: GTLN - GTNN CỦA HÀM SỐ',date:'SGK',link:'https://www.youtube.com/watch?v=qCKviOxmmeE',type:'video'},
    {name:'Bài 1.1: VECTO KHÔNG GIAN (P1)',date:'SGK',link:'https://www.youtube.com/watch?v=OA3vVKt71zM',type:'video'},
    {name:'Bài 1.2: VECTO TRONG KHÔNG GIAN (P2)',date:'SGK',link:'https://www.youtube.com/watch?v=Qh4UjgpfA1U',type:'video'},
    {name:'BÀI 1: PHƯƠNG TRÌNH MẶT PHẲNG P1',date:'SGK',link:'https://www.youtube.com/watch?v=_nnpTm2Ju2o',type:'video'},
    {name:'BÀI 2: PHƯƠNG TRÌNH MẶT PHẲNG P2',date:'SGK',link:'https://www.youtube.com/watch?v=s4eXhU4B5gU',type:'video'},
    {name:'BÀI 3: PHƯƠNG TRÌNH MẶT PHẲNG P3',date:'SGK',link:'https://www.youtube.com/watch?v=Fcn3odFMHK0',type:'video'}
  ]},
  {id:'sgk_su',name:'SGK LỊCH SỬ',desc:'Sách giáo khoa · Video bài giảng',icon:'📜',color:'violet',group:'sgk',lessons:[
    {name:'Bài 1: LIÊN HỢP QUỐC',date:'SGK',link:'https://www.youtube.com/watch?v=mwwDY8qR8Mw',type:'video'},
    {name:'Bài 2: TRẬT TỰ THẾ GIỚI TRONG CT LẠNH',date:'SGK',link:'https://www.youtube.com/watch?v=7u2UtWcCeIM',type:'video'},
    {name:'Bài 3: TRẬT TỰ THẾ GIỚI SAU CT LẠNH',date:'SGK',link:'https://www.youtube.com/watch?v=-LbgOYSkbUo',type:'video'},
    {name:'BÀI 4: SỰ RA ĐỜI ASEAN',date:'SGK',link:'https://www.youtube.com/watch?v=qwL-okw4NnQ',type:'video'},
    {name:'BÀI 5: CỘNG ĐỒNG ASEAN',date:'SGK',link:'https://www.youtube.com/watch?v=KiX48BEfndY',type:'video'},
    {name:'BÀI 6: CÁCH MẠNG THÁNG TÁM 1945',date:'SGK',link:'https://www.youtube.com/watch?v=zVIrrHq8sMc',type:'video'},
    {name:'BÀI 7: KHÁNG CHIẾN CHỐNG PHÁP',date:'SGK',link:'https://www.youtube.com/watch?v=Mylhkl4aEP8',type:'video'}
  ]}
];

const THAY_CHI = {
  id:'thay_chi',name:'TOÁN THẦY CHÍ 12',desc:'Toán · Thầy Nguyễn Quốc Chí',icon:'👨‍🏫',color:'red',group:'thaychi',
  lessons:[
    {name:'[TIẾT 1] Tìm khoảng Đồng biến, Nghịch biến',date:'CH1',link:'https://drive.google.com/file/d/1chkipC3u4b6v34MqTdMO0ETJRtVLYx6b/view',type:'video'},
    {name:'[TIẾT 2] Bài toán thực tế đơn điệu',date:'CH1',link:'https://drive.google.com/file/d/1fZ6pK6OGAO_WcKzRXz0JN7SPfWai1Di_/view',type:'video'},
    {name:'LUYỆN TẬP TRẮC NGHIỆM ĐÚNG SAI',date:'CH1',link:'https://drive.google.com/file/d/1YXBx94QxVsqm6WGsV936m8HOWMNQW9ea/view',type:'video'},
    {name:'[TIẾT 3] Biện luận tính đơn điệu (buổi 1)',date:'CH1',link:'https://drive.google.com/file/d/1gvazwf-TSaQgZ5fIH1QIet5bxBAiZ0oZ/view',type:'video'},
    {name:'Biện luận tính đơn điệu (buổi 2)',date:'CH1',link:'https://drive.google.com/file/d/1upygs3FzPDvHmjM_9kazm4AxpnI5PuHf/view',type:'video'},
    {name:'TỔNG ÔN TÍNH ĐƠN ĐIỆU',date:'CH1',link:'https://drive.google.com/file/d/1I29o23EQjRRAuU7RdqMfRtan2mjFGAp4/view',type:'video'},
    {name:'[TIẾT 1] Xác định cực trị',date:'CH1',link:'https://drive.google.com/file/d/1Bs3_-ENQbL5Nbei5Cyjkc5LXW5ZOsdZn/view',type:'video'},
    {name:'[TIẾT 2] Khảo sát hàm số Mũ, Logarit',date:'CH1',link:'https://drive.google.com/file/d/13igE-5PcN8FX4IOkg1V2tMNC3HIqJKcZ/view',type:'video'},
    {name:'[TIẾT 1] Tìm GTLN, GTNN trên đoạn',date:'CH1',link:'https://drive.google.com/file/d/1cfxyRKJd-5xSD9SqOkMVI53A3UI56S9R/view',type:'video'},
    {name:'[TIẾT 2] Tìm GTLN, GTNN trên khoảng',date:'CH1',link:'https://drive.google.com/file/d/1biNLghnW6lvxKCzXb67Za7OMFjvOAAoU/view',type:'video'},
    {name:'[TIẾT 1] Xác định tiệm cận đứng, ngang',date:'CH1',link:'https://drive.google.com/file/d/1cqVnXZZ_REo4aee2hemCFZybi_Y5z1Sz/view',type:'video'},
    {name:'[TIẾT 1] KHẢO SÁT ĐỒ THỊ HÀM BẬC 3',date:'CH1',link:'https://drive.google.com/file/d/1ioD-_oQWtHrZ1Hi6dCD4tnBhsxAY6uU2/view',type:'video'},
    {name:'[TIẾT 1] Tính đơn điệu của hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/1HIHKSL6i3u8VrQ3IhVpCIPkC1TCBGDu3/view',type:'video'},
    {name:'Cực trị hàm hợp (Buổi 1)',date:'CH1',link:'https://drive.google.com/file/d/1OrNgOkMWXPMQHxio3RXF-LLphRB9SQTx/view',type:'video'},
    {name:'Minmax hàm hợp',date:'CH1',link:'https://drive.google.com/file/d/1B35vBqXzjj7zJGvGKolRwnWVdaHtTz95/view',type:'video'},
    {name:'Tiết 1: Cực trị hàm y=|f(x)|',date:'CH1',link:'https://drive.google.com/file/d/1bv0f_TQlMFzQkIZzteuh7jy3MuonY7sy/view',type:'video'},
    {name:'Tiết 2: Cực trị hàm y=f(|x|)',date:'CH1',link:'https://drive.google.com/file/d/11lCv-RzYeYBJYXzGB0ZPbQRpKheK5yEJ/view',type:'video'},
    {name:'[TIẾT 1] NGUYÊN HÀM CƠ BẢN',date:'CH4',link:'https://youtu.be/a6A-sqViYDo',type:'video'},
    {name:'[TIẾT 2] NGUYÊN HÀM HÀM HỢP',date:'CH4',link:'https://youtu.be/prCq7C6iNss',type:'video'},
    {name:'[TIẾT 3] NGUYÊN HÀM HỮU TỈ',date:'CH4',link:'https://youtu.be/ScnKHTtPOxQ',type:'video'},
    {name:'TÍNH TÍCH PHÂN',date:'CH4',link:'https://youtu.be/3kgqyFEFzkc',type:'video'},
    {name:'[TIẾT 1] XÁC ĐỊNH YẾU TỐ MẶT PHẲNG',date:'CH5',link:'https://youtu.be/HjSwPiPdy8M',type:'video'},
    {name:'[TIẾT 1] LẬP PT MẶT CẦU',date:'CH5',link:'https://youtu.be/h3iitITyzsM',type:'video'},
    {name:'[TIẾT 1] XÁC SUẤT CÓ ĐIỀU KIỆN',date:'CH6',link:'https://youtu.be/_JPLqrLhuPw',type:'video'},
    {name:'TL: [TIẾT 1] Đồng biến, Nghịch biến',date:'TL1',link:'https://drive.google.com/drive/folders/16phOwE1M58dluU3EXqXOdSYQ-SbLCE6M',type:'tailieu'},
    {name:'TL: Xác định cực trị',date:'TL2',link:'https://drive.google.com/drive/folders/1A6OGMMZs7NaifQcjTRFn01SyLaJQfNVv',type:'tailieu'},
    {name:'TL: GTLN-GTNN trên đoạn',date:'TL3',link:'https://drive.google.com/drive/folders/1YG46gJsxJy8AmgxdZI3Wlk8Mv-E5hPX0',type:'tailieu'},
    {name:'BTVN: [TIẾT 1] Đồng biến, Nghịch biến',date:'BTVN1',link:'https://drive.google.com/drive/folders/1HlwHHkKkdXmFLNrDFRPgx7eE1b61o1s3',type:'btvn'},
    {name:'BTVN: Xác định cực trị',date:'BTVN2',link:'https://drive.google.com/drive/folders/1EkOMANT-f6r2LqR-DIqw93Kq5vaR0nXj',type:'btvn'},
    {name:'Chữa BTVN: [TIẾT 1] Đơn điệu',date:'CB1',link:'https://drive.google.com/file/d/1kkHZlQXccIseM7kTUvR4oYGiYPXvE1UQ/view',type:'btvn'}
  ]
};

const CO_SEN = {
  id:'co_sen',name:'SỬ CÔ HƯƠNG SEN',desc:'Lịch sử · Cô Hương Sen · Lớp 12',icon:'📜',color:'pink',group:'cosen',
  lessons:[
    {name:'Bài 1 Liên hợp quốc',date:'Bài 1',link:'https://youtu.be/-LoBn5WekkM',type:'video'},
    {name:'Đề số 1',date:'Đề 1',link:'https://youtu.be/iTv2dbhB6kc',type:'video'},
    {name:'Bài 2',date:'Bài 2',link:'https://www.youtube.com/playlist?list=PL3ZewEXRtOFRUMxG3J0r_trFcARyRhHtq',type:'video'},
    {name:'Đề số 2',date:'Đề 2',link:'https://youtu.be/mX9_NYv4l1s',type:'video'},
    {name:'Bài 3 Trật tự thế giới sau chiến tranh',date:'Bài 3',link:'https://youtu.be/BB74hjcOXHY',type:'video'},
    {name:'Bài 4 Sự ra đời ASEAN P1',date:'Bài 4',link:'https://youtu.be/XTVAnMGdZgs',type:'video'},
    {name:'Bài 4 Sự ra đời ASEAN P2',date:'Bài 4',link:'https://youtu.be/ccDyaWyTK4g',type:'video'},
    {name:'Bài 5 Cộng đồng ASEAN',date:'Bài 5',link:'https://youtu.be/vufhxU2oWb0',type:'video'},
    {name:'Bài 6 CMT8 - 1945 P1',date:'Bài 6',link:'https://youtu.be/sNc4GKb8UPQ',type:'video'},
    {name:'Bài 6 CMT8 - 1945 P2',date:'Bài 6',link:'https://youtu.be/3h_-nbnNrrQ',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P1',date:'Bài 7',link:'https://youtu.be/TFhooXZJTro',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P2',date:'Bài 7',link:'https://youtu.be/xqS76zxWhHA',type:'video'},
    {name:'Bài 7: Kháng chiến chống Pháp P3',date:'Bài 7',link:'https://youtu.be/4hWfSgPxC2Q',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P1',date:'Bài 8',link:'https://youtu.be/38MhsbYfRUc',type:'video'},
    {name:'Bài 8: Kháng chiến chống Mỹ P2',date:'Bài 8',link:'https://youtu.be/asEsharpkbk',type:'video'},
    {name:'Bài 9: 1975 - Nay',date:'Bài 9',link:'https://youtu.be/G46xH-XQcgY',type:'video'},
    {name:'Bài 10: Việt Nam từ 1986 đến nay',date:'Bài 10',link:'https://www.youtube.com/playlist?list=PL3ZewEXRtOFTzOO5uJxdMd-7_0iybgNdS',type:'video'}
  ]
};
